### ISSUE TITLE
Kill a running query

### ISSUE THREAD

**Issue by noplay** [sosedoff/pgweb#10]
Nice application, 

I have an enhancement suggestion. You can add an option in order to kill a running query.

Have a nice day

**Comment by kespindler** [comment]
It'd also be useful to know how long an ongoing query has been running. A simple javascript timer on the page would suffice for this purpose.

**Comment by sosedoff** [comment]
@kespindler javascript timer would be irrelevant in case if you run a query on non-local servers. Results
table also takes some time. So if we want to have query execution time, it has to be done via backend.

**Comment by sosedoff** [comment]
Stopping a running query is currently in works.

**Comment by codeBearer** [comment]
Is it possible to use pgweb as a service? Or what should be the proper way to deploy it?

**Comment by spaquet** [comment]
+1

**Comment by flesler** [comment]
I think this should be pretty easy to make.

You already made the Activity tab, it has which one is active and what's the pid.
I imagine active queries having a "kill" button that executes this:

```sql
SELECT pg_cancel_backend(pid);
```
And Activity tab is refreshed. That should do no?

**Comment by sosedoff** [comment]
Implemented in master
