### ISSUE TITLE
Visual analyze

### ISSUE THREAD

**Issue by zhulik** [sosedoff/pgweb#101]
Is it possible to add visual analylize like in pgadmin3?

offtop: 9.4 support? I have 9.4 on all my machines, pgweb works with it, but on installation wiki page 9.3 is latest supported

**Comment by sosedoff** [comment]
> Is it possible to add visual analylize like in pgadmin3?
of course it is! all PRs are welcome

> offtop: 9.4 support?
should be working fine with anything 9.x at this point
