### ISSUE TITLE
Postgis types support

### ISSUE THREAD

**Issue by zhulik** [sosedoff/pgweb#102]
Is it possible to add postgis types support?

**Comment by sosedoff** [comment]
Closing this for now since postgis really has nothing to do with pgweb. Unless the question was more related to the UI part. Feel free to reopen though.

**Comment by dersteppenwolf** [comment]
It would be great some kind of integration with postgis like "PostGIS Preview" http://chriswhong.com/data-visualization/introducing-postgis-preview/

**Comment by pramsey** [comment]
Yes, this is really about UI support. DBeaver and PgAdmin both can show "map views" of query results, which is a super feature.

**Comment by frafra** [comment]
It is possible to convert a WKB to a WKT and then to a Leaflet feature using https://github.com/arthur-e/Wicket, or to a GeoJSON. There are some WKB to WKT converters around as well.

Converting from WKB to WKT could be done on the Postgres side as well, but it wouldn't be just a UI issue then.

**Comment by onionhammer** [comment]
This would be a very cool feature
