### ISSUE TITLE
Feature: Access multiple databases

### ISSUE THREAD

**Issue by sammcj** [sosedoff/pgweb#106]
It would be great if you could authenticate to pgweb, then access a number of databases once logged in.

I.e. you might want to give access to some developers and they might need to access several databases on the same (or different) servers, each database will have its own set of permissions.

I guess a simple role based authentication would be fantastic?

**Comment by sosedoff** [comment]
This makes sense, yes, but unfortunately pgweb does not use any sort of database to store its own settings or state so having any kind of authentication system will require it to have one. I was thinking about it for a while now since i sometimes too want to use pgweb in multiple "sessions". Adding this feature will require a significant refactoring effort so its not something i can work on right now, unless you are willing to help out on your end. Feel free to reopen the issue.

**Comment by smurfpandey** [comment]
@sosedoff About the multiple pgweb sessions in different tabs, I have implemented this in my fork [mysqlweb](https://github.com/smurfpandey/mysqlweb).
Basically I am storing a UUID for each new connection, and then sending that UUID on the frontend. On every API request, that UUID is passed in header.

1. Return UUID when new connection is created: https://github.com/smurfpandey/mysqlweb/blob/master/client.go#L50
2. Pass this UUID on each API call: 
https://github.com/smurfpandey/mysqlweb/blob/master/static/js/app.js#L1430
https://github.com/smurfpandey/mysqlweb/blob/master/static/js/app.js#L57
3. On the backend get the the DB connection for this UUID
https://github.com/smurfpandey/mysqlweb/blob/master/api.go#L128

Hope this helps :)

**Comment by sosedoff** [comment]
@smurfpandey thanks, yeah i get that, but i think the original question was not only related to database sessions, but also involves some sort of permission model. Anyways, i was hoping to get to session implementation soon.

**Comment by sarink** [comment]
Why would we need to complicate things with a permissions and roles module? What about just building a simple portal screen that made you specify the connection string `postgres://...`, and once you did it connected to that db? For convenience, save a list of previously connected database url strings in localstorage. This _seems_ like it would be a relatively low level of effort, but perhaps I'm mistaken. What do you think, @sosedoff ?

**Comment by JoeKendall** [comment]
To bump a very old thread... 

Could it be an idea to pass in a number of URL schemes, then they can be loaded into a dropdown on the scheme tab when logging in? 

Not as seamless, but could get people closer to having access to multiple databases without entering credentials multiple times?

Just a thought. :)
