### ISSUE TITLE
bigint columns truncated to Javascript limits (52 - 53 bits)

### ISSUE THREAD

**Issue by skabbes** [sosedoff/pgweb#108]
If you have columns that are bigint, they are truncated when displaying.  This will only happen if the values are larger the js limit.

```sql
-- where amby_id is of type bigint
select amby_id, amby_id::text from amby;
```

<img width="344" alt="screenshot 2016-01-06 11 08 44" src="https://cloud.githubusercontent.com/assets/592178/12151910/649638ac-b466-11e5-8ade-549aa00e1a56.png">

**Comment by sosedoff** [comment]
Perhaps this could be solved by casting all rows' values to strings in JSON response. Its not the best solution (and def not the correct one), but otherwise it'll require some bignum js library to be brought in. Any other ideas ?

**Comment by skabbes** [comment]
I haven't really dug into the code much, so bear with my naming...

From a quick glance, it seems like you have the column names only, but I believe postgres allow you to extract the type information as well as the column names.  So perhaps we could add another field to [Result](https://github.com/sosedoff/pgweb/blob/master/pkg/client/result.go#L12-L15) enumerating the types as well.

Then when you marshal the data to json, you could take the types into account and bigint should be send down as strings.

Another possible solution would be to parse the response form the API with something like [json-bigint](https://github.com/sidorares/json-bigint).

**Comment by sosedoff** [comment]
Yeah, i did experiment with automatic encoding of bigint's as strings and it works fine, will probably fix the issue sometime this week.

**Comment by skabbes** [comment]
Sounds great - thanks so much.  This is an awesome product I use daily.

**Comment by sosedoff** [comment]
@skabbes try latest master, the issue should be fixed now.
