### ISSUE TITLE
Missing hyperlinks on foreign key

### ISSUE THREAD

**Issue by bill-myers** [sosedoff/pgweb#11]
This project is missing the most important feature of a database GUI: the ability to view related records...

Basically whenever a foreign key is defined, the value should be linked to the row in the referenced table. Also, ideally, there should be a button to automatically join on foreign keys.

Without this feature, easy navigation is impossible.

**Comment by sosedoff** [comment]
Closing this issue unless anyone is interested on working on the feature  / @cbandy @bill-myers
