### ISSUE TITLE
Database for live demo

### ISSUE THREAD

**Issue by lukecyca** [sosedoff/pgweb#116]
This looks like a very nice project! 

I tried to use the live demo, but didn't see any login information to be used. 

Did I miss it?
Do I have to supply my own Internet-exposed postgres server in order to use the live demo?

**Comment by sosedoff** [comment]
Yeah, you will have to provide a sample database in order to connect using demo instance. The reason why there's no database is because demo is hosted on heroku and they dont provide ability to create read-only users, at least not on free plan.

**Comment by lukecyca** [comment]
Thanks for the clarification.

Again, awesome project.

**Comment by ArturFormella** [comment]
Do you save connection data somewhere? :)

**Comment by sosedoff** [comment]
What do you mean? The demo site does not save any data that passes through it, you can check the source code.

**Comment by rdp** [comment]
I came here with the same question...it feels like it either wants a "actual demo" (since I can't connect to local DB's from the demo) or else some kind of...youtube demo or screenshot demo, to see how it looks...thanks!
