### ISSUE TITLE
Explicitly set timeout to a very high value in javascript code

### ISSUE THREAD

**Issue by tylerlong** [sosedoff/pgweb#117]
I find that different browsers might have different timeout values. If you don't set timeout in javascript code,  the browser will set one.

Ref:

> http://stackoverflow.com/questions/4148830/what-is-jquerys-ajax-default-timeout-value
> http://stackoverflow.com/questions/7297833/how-long-will-the-browser-wait-after-an-ajax-request

I request this to solve an issue I meet. I use the WebView control of Cocoa, it is like an embedded version of Safari. But unfortunately it has a very small default timeout value. And whenever I run a long running sql query, the request timeouts and the UI freezes for ever.

Let me know if you think what I said above makes sense. 

Thank you very much!

Tyler

**Comment by tylerlong** [comment]
Or can we show a popup message to tell the user that it has been timeout. It's better than to let the user wait for ever.

**Comment by sosedoff** [comment]
I set timeout to 2 minutes, that should be enough for most queries. Use master branch to verify the fix

**Comment by tylerlong** [comment]
@sosedoff Could we make it 5 minutes? There is no disadvantages to set a higher value.

And by the way, if it does timeout, could we show a popup to notice the user?

Thank you for your hard work!  :+1:

**Comment by sosedoff** [comment]
Done
