### ISSUE TITLE
Add ability to resize custom sql query window

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#118]
Right now it cant be resized and makes it harder to write bigger queries.

**Comment by sosedoff** [comment]
Speaking of resizes, other components should be able to be resized, not just the query window. Planning on working on it in the next releases (will open another issue).

**Comment by ryantuck** [comment]
any timeline on this? as it stands it's basically the only gripe i have with an otherwise awesome tool.

**Comment by sosedoff** [comment]
Will work on it this week probably

**Comment by ELI7VH** [comment]
any updates?

**Comment by sosedoff** [comment]
Unfortunately no, i've been very busy with work and have no time for any updates.
