### ISSUE TITLE
Stuck saying "Please wait, query executing..."

### ISSUE THREAD

**Issue by brian-vogogo** [sosedoff/pgweb#119]
When running some ad-hoc queries, pgweb shows 'Please wait, query executing". No results grid shown. Browser still responding. Javascript console showing:

```
Uncaught TypeError: Cannot read property 'forEach' of null
buildTable @ app.js:242
(anonymous function) @ app.js:485
$.ajax.success @ app.js:71
j @ jquery.js:2
k.fireWith @ jquery.js:2
x @ jquery.js:4
(anonymous function) @ jquery.js:4
```

Behaviour is repeatable. Not sure what is common about the queries it fails on. Usually they are more complex.

**Comment by brian-vogogo** [comment]
Simplifying the select list seems to help (e.g. changing from `t.*` to `count(*)`)

**Comment by sosedoff** [comment]
I think i just fixed this bug in master, please give it a try.

**Comment by brian-vogogo** [comment]
I think that fixed it. Will reopen if I see it again. Thanks!

**Comment by EamonZhang** [comment]
```
pgweb --version
Pgweb v0.16.2 (git: e63945ee7182435a729f22a4203e2f15d00f6350) (go: go1.22.8) (build time: 2024-11-02T16:22:35Z) (arch: linux/amd64)
```
Please wait, query is executing...
ERROR: Query timeout after 300s
