### ISSUE TITLE
Long table names wrapping

### ISSUE THREAD

**Issue by brian-vogogo** [sosedoff/pgweb#120]
![image](https://cloud.githubusercontent.com/assets/9039521/12464092/94245d0a-bf84-11e5-9d8c-30639f03ebd4.png)

**Comment by sosedoff** [comment]
Hi, this issue is a basic regression and will be fixed in the next minor release. Thanks for the feedback.

**Comment by sosedoff** [comment]
Fixed

**Comment by openchristianlibrary** [comment]
I am having the same issue in the current release with long table names. Looks exactly like the screenshot from the OP.
