### ISSUE TITLE
Have bookmarkable/persistent  URLs

### ISSUE THREAD

**Issue by flesler** [sosedoff/pgweb#121]
This is not a critical one, but it'd be nice if (for example) clicking the Activity tab would also change the path to something like "/activity".

It's a common feature of single-page web apps like this.

**Comment by sosedoff** [comment]
Hi and thanks for the feedback. I agree that having more friendly links is better and helps
a lot when sharing pages, but unfortunately its not a priority for pgweb (or myself) at the moment.
I see that this feature could be easily implemented with any sort of routing/lightweight js framework, perhaps even with vanilla jquery. Will keep this open for now, feel free to contribute if you have any
interest in making this feature happen.
