### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by flesler** [sosedoff/pgweb#122]
Hi, you should document the supported shortcuts and maybe add some more.

By experimenting I discovered `ctrl+enter` for submitting queries. This info is key for the wiki.
Is there a similar shortcut for explaining?

You could also support the ones pgAdmin does, `F5` for querying and `F7` for explaining.

There are probably more undocumented and useful+missing shortcuts

**Comment by sosedoff** [comment]
Added wiki page regarding keyboard shortcuts (there only few available): https://github.com/sosedoff/pgweb/wiki/Keyboard-Shortcuts
