### ISSUE TITLE
Show table triggers

### ISSUE THREAD

**Issue by gauravarora** [sosedoff/pgweb#124]
I don't think this currently exists but if it does please feel free to smack me and close.

I'd like to be able to see what triggers are attached to a particular table. I think the best place for this information is the structure tab.

**Comment by sosedoff** [comment]
Right now structure tab is very simple and does not have ability to display data from multiple "sources", i.e it just displays a single table as any other view. There's a need to rebuild structure view to include more data but i don't think its a priority for me right now, at least not until i get to refactor the way different table views are displayed. I'll keep this issue open for now. If you wish to help out - please do and open a PR and i will happily review your contributions. Thanks.

**Comment by sosedoff** [comment]
Closing due to no action (im personally not interested on working on this feature)
