### ISSUE TITLE
Quick database switch

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#125]
Add ability to switch between available databases via some sort of dropdown. This is super useful when doing local dev and having to switch between different browser tabs or even pgweb sessions. This should not be very tricky to implement since database connection object saves the full connection url, so maybe there's need to expose another endpoint like `/api/switchdb` to handle this. One of the reasons for to have a new endpoint is when api cant return the full connection string for security reasons while running in multi-session mode. New feature needs to have support for bow regular and ssh connections.

**Comment by akarki15** [comment]
agreed. i have to constantly go back to the login screen and change the database name to switch

**Comment by akarki15** [comment]
i can look into adding this feature

**Comment by sosedoff** [comment]
Implemented in master. UI is not superb, but it does the job. UI will be improved in the next releases.
