### ISSUE TITLE
Camel case column names are broken in search

### ISSUE THREAD

**Issue by epeli** [sosedoff/pgweb#126]
I have a database where columns are named with a camel case convention. It seems that the search does not respect that.

Here the column name is `lastName` but the search error lists it as `lastname`.

![pgwebcamelcase](https://cloud.githubusercontent.com/assets/225712/12704301/96bf21c8-c860-11e5-8b83-dc95de5a2a29.png)

I know should find something with that query.

Using version v0.9.1 d3d408bc684f3e2c36f86bea2f1e760d68215183 and `9.4.5-2.pgdg12.4+1` Postgresql on Ubuntu Trusty.

**Comment by sosedoff** [comment]
Try running pgweb from master, it should have a fix in place.
