### ISSUE TITLE
Close Connection

### ISSUE THREAD

**Issue by danilobuerger** [sosedoff/pgweb#127]
I might be blind, but how do i close a connection from the frontend?

**Comment by sosedoff** [comment]
You're not blind, there's no button to close connection. If you're using single connection mode you can just stop/kill the app.

**Comment by danilobuerger** [comment]
I am using the session mode.
So in that case, this is a feature request for a "Close Connection" button :).

**Comment by sosedoff** [comment]
Cool, i'll look into it and perhaps add the feature to the next release

**Comment by danilobuerger** [comment]
I can help out if you want.

**Comment by sosedoff** [comment]
Fix has been pushed to master. Please verify if it works for you.

**Comment by danilobuerger** [comment]
Closing the connection works as expected. However there seems to be a glitch with the interface:

1. Log in
2. Click on Connect
3. Click on Cancel
4. Click on Disconnect

Now the connection is closed, but i have the ability to Cancel again. Which brings me back to the interface with all the loaded data still being presented. However new queries are errored out with "ERROR: sql: database is closed".

**Comment by sosedoff** [comment]
Try now

**Comment by danilobuerger** [comment]
Looking good!

**Comment by sosedoff** [comment]
Cool. Closing for now then.
