### ISSUE TITLE
See records affected by update/insert/delete

### ISSUE THREAD

**Issue by brianlow** [sosedoff/pgweb#129]
When running
```
  update mytable set color = 'blue'
```
would be nice to show 'UPDATE 5' instead of 'No records found'.

**Comment by sosedoff** [comment]
As far as i know there's no alternative to MySQL's `mysql_affected_rows` function in PostgreSQL.
http://dev.mysql.com/doc/refman/5.7/en/mysql-affected-rows.html

**Comment by brian-vogogo** [comment]
psql does it somehow:
```
$ psql mydb
psql (9.3.9)
Type "help" for help.

mydb=# update mytable set color = 'blue'
UPDATE 3
```
but not sure how it does it.

**Comment by sosedoff** [comment]
i can see that it somehow does it too, but there are no extra sql queries in the server log, so it must be something internal. I'll have a look later today.

**Comment by cbandy** [comment]
https://golang.org/pkg/database/sql/#Result

**Comment by sosedoff** [comment]
Try master, it should now display number of affected rows if sql statement starts with `UPDATE` or `DELETE`.

**Comment by brian-vogogo** [comment]
:+1: Looks good!
