### ISSUE TITLE
How to disable tabs like history and activity without self building the code.

### ISSUE THREAD

**Issue by imkritesh** [sosedoff/pgweb#136]
I want to remove history and activity tabs from pgweb. Is there some way to do so without self building the code. Where does history and activity data gets stored?
 I am using executable for linux.

**Comment by sosedoff** [comment]
Query history is stored in memory while pgweb is running. Activity data is actually not something that is being stored and comes directly from postgresql server. Right now there's no way to disable both these features so your only option is to build from source.

**Comment by imkritesh** [comment]
Thanks.

**Comment by sosedoff** [comment]
FYI, if you want to rebuild pgweb without activity and history tabs, you can remove the following lines here (https://github.com/sosedoff/pgweb/blob/master/static/index.html#L27-L28) and then build pgweb:

```
make build     # build for current OS
make release # build for all supported OS
```

**Comment by imkritesh** [comment]
Changes in static/index.html are not reflecting after building. I can not figure out whats the problem?
commands I have used:
make setup
go get
make build

**Comment by sosedoff** [comment]
Try running `make assets` first.

**Comment by imkritesh** [comment]
I have tried that too. Even if I remove index.html from static folder it still works and no change is reflected.

**Comment by sosedoff** [comment]
Hm, i just did the following:

1. opened index.html file, removed both tabs (activity/history)
2. ran `make build` (which runs asset build task as well)
3. started pgweb from current dir `./pgweb`

and both tabs are gone from the interface. are you sure you're not starting your system-wide pgweb version instead of freshly built one?
