### ISSUE TITLE
Sanitize SQL queries where possible

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#137]
Right now its pretty easy to make an SQL injection

**Comment by joncrlsn** [comment]
I don't understand this "bug".  This tool lets you run any SQL you want.  There is no need to inject SQL into another SQL statement when you can run any SQL you want directly.

**Comment by sosedoff** [comment]
I opened this ticket from a private conversion (as a reminder), but i think its no longer valid. In other words, pgweb should not be used in untrusted environments, or used with a read-only user. Closing this for now.
