### ISSUE TITLE
schema support?

### ISSUE THREAD

**Issue by swuecho** [sosedoff/pgweb#14]
I can 'set search_path= schema' and run the query through the browsers, but the tables names show in the left do not change. 

thanks.

**Comment by jerome-peng** [comment]
yeah,I just ran into this problem also. My database doesn't use the public schema, so I can run queries but cannot select any tables.

**Comment by jerome-peng** [comment]
Does this proble solved? 
I use pgweb_windows_386 version 0.5.0, schema support?

**Comment by gglanzani** [comment]
Is this also the reason why I cannot see materialized views?

**Comment by alfonsodev** [comment]
+1

**Comment by suedered** [comment]
:+1: I just ran into this problem also. My database doesn't use the public schema, so I can run queries but cannot select any tables.

**Comment by sosedoff** [comment]
hang tight, im working on it.

**Comment by alfonsodev** [comment]
:+1:  if you want help push the branch with your progress or your idea how would you like to implement it, 
I really would like to see this feature, wouldn't mind to help. 
thanks for your effort! I use this tool every day. :)

**Comment by brian-vogogo** [comment]
:+1: Would like this schema support. Willing to help.

**Comment by sammcj** [comment]
+1

**Comment by sosedoff** [comment]
Implemented in master
