### ISSUE TITLE
long table name/object name breaking the format in sidebar

### ISSUE THREAD

**Issue by doomsplayer** [sosedoff/pgweb#144]
![image](https://cloud.githubusercontent.com/assets/998606/13370982/2baae9b2-dd55-11e5-9087-44d594fb4ab0.png)
![image](https://cloud.githubusercontent.com/assets/998606/13370985/51ffd7d0-dd55-11e5-8ae0-f80056b2e460.png)
seq name `namecheap_subscription_periods_id_seq` is so long that it becomes a newline rather than the same line with the circle

**Comment by sosedoff** [comment]
This issue has already been fixed in master and will be available in the next release.

**Comment by doomsplayer** [comment]
@sosedoff thanks
