### ISSUE TITLE
Support for Client Certificates

### ISSUE THREAD

**Issue by 64b2b6d12b** [sosedoff/pgweb#145]
When a database is configured to only allow Client Certificate connections, pgweb will fail to connect and we see the following error `pq: connection requires a valid client certificate`. Is there a way pgweb can support Client Certificate connections?

**Comment by sosedoff** [comment]
This seems to be a legit issue. Btw, how are you connecting to your server? Via host/port/etc or via database uri string?

**Comment by sosedoff** [comment]
No feedback. Closing.
