### ISSUE TITLE
Make tabs sticky

### ISSUE THREAD

**Issue by akarki15** [sosedoff/pgweb#146]
It would be nice to make tabs sticky- it is annoying that whenever I change table, it defaults to `Rows`. A lot of times I am just concerned with the `Structure` or schema of the table. 

Hence making the tabs sticky is a quick yet effective solution to this.

**Comment by sosedoff** [comment]
Thanks for the feedback. This change should be a fairly easy one, i might get to work on it this week unless you have a PR ready.

**Comment by akarki15** [comment]
I don't have a PR yet, so feel free to work on it!

**Comment by sosedoff** [comment]
Implemented. Should be soon in master.
