### ISSUE TITLE
responsive search bar

### ISSUE THREAD

**Issue by akarki15** [sosedoff/pgweb#148]
the search bar gets all weird when the window is resized. i am running chrome 49.0.2623.112 (64-bit) on a mac os x 10.10.3 (yosemite). this is a low hanging fruit -

![screen shot 2016-04-16 at 11 58 30 am](https://cloud.githubusercontent.com/assets/3751173/14582139/d2b7c0fe-03ca-11e6-945d-34aef23b6ffe.png)

**Comment by sosedoff** [comment]
@akarki15 if you'd like to fix this - go ahead. otherwise let me know if i can close the issue, it hasn't been a problem for me afaik.

**Comment by akarki15** [comment]
You can close this one
