### ISSUE TITLE
AngularJS ?

### ISSUE THREAD

**Issue by abourget** [sosedoff/pgweb#15]
I was thinking of angularifying the app, I think it would scale better. Would you be opposed ?

**Comment by kenhahn85** [comment]
Is this conversion still in progress? ReactJS has taken the JS community by storm, and is a very maintainable way to build front-end apps.

**Comment by abourget** [comment]
I'm doing more Polymer these days :) You're free to pitch it what you want.. I think we should close this one.

Someone else will take leadership in doing a solid UI..
