### ISSUE TITLE
Specify search_path (schema via cmd)

### ISSUE THREAD

**Issue by jonaz** [sosedoff/pgweb#150]
I would like a --search-path command line argument which connects to the correct schema.

Currently im launching pgweb programaticly and would like an option to run
set search_path to XXXX; so i dont have to input it in the webui before running my selects.

```
		Run("pgweb",
			"--port", db.Port(),
			"--host", db.Host(),
			"--user", db.Username(),
			"--pass", db.Password(),
			"--db", db.Db(),
			"--ssl", "disable",
		)
```

**Comment by sosedoff** [comment]
Since you're running pgweb programmatically, you can make a call to the api to set the schema. Here's an example:

```
curl http://localhost:8081/api/query?query=SET%20search_path%20TO%20myschema
```

**Comment by jonaz** [comment]
Oh, thanks. Closing this as this solves my issue!
