### ISSUE TITLE
Can't get pgweb running from docker with wiki config

### ISSUE THREAD

**Issue by kefirchik** [sosedoff/pgweb#151]
```docker run``` prints out that it starts at 0.0.0.0:8081,but in wiki I see localhost:8080 and nothing of it works

It works when I change port to 8081 ```docker run -p 8081:8081 ...```

**Comment by sosedoff** [comment]
You should be using port 8081, i think i havent updated wiki to reflect the change in default port used by pgweb.

**Comment by kefirchik** [comment]
Thanks for the response I fugured it out and update comment :+1:

**Comment by kefirchik** [comment]
Everything works fine with port 8081
