### ISSUE TITLE
docker run failing

### ISSUE THREAD

**Issue by joeblew99** [sosedoff/pgweb#152]
The run command to boot up the web ui is failing.
As per wiki instructions: https://github.com/sosedoff/pgweb/wiki/Docker

I am not that familiar with docker, but it may be to do with the fact i am using the latest docker for mac on OSX that uses xhyve (and not virtual box), and it maybe an API change with dockers latest release ?

Docker Information
API Endpoint: dockerapi
API Version: 1.23
Docker version: 1.11.1

````

x-MacBook-Pro:pgweb apple$ docker run -p 8081:8081 --link db:db -e DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
docker: "run" requires a minimum of 1 argument.
See 'docker run --help'.

Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
x-MacBook-Pro:pgweb apple$ 

````

**Comment by sosedoff** [comment]
I updated the wiki to include the proper command. It was missing the image name (sosedoff/pgweb).
