### ISSUE TITLE
Multiple Query tabs

### ISSUE THREAD

**Issue by coussej** [sosedoff/pgweb#154]
Hello,

first of all, awesome project :+1: . I've been looking for a slick open-source postgres interface for a while now, and this seems to be going in the right direction.

Therefore, may I suggest a feature: allow for multiple query tabs to be open at the same time, like you can have in SQL server, HeidiSQL, ... I think I'm not the only one who like to have different queries + result sets open at the same time :smile: 

Thanks!

**Comment by sosedoff** [comment]
There's a multi-session support available right now, but its slightly different from what you're asking. Although it allows you to run number of connection with different servers in the same browser.

Thanks for the suggestion, i'll look into it as soon as i have spare time.

**Comment by sosedoff** [comment]
This feature would require a major overhaul of the current backend and frontend implementations, so closing this until better times.

**Comment by smurfpandey** [comment]
@sosedoff I implemented the same feature in mysqlweb using bootstrap-tabs. Every tab contains it's own query window & result window.
If it helps:
https://github.com/smurfpandey/mysqlweb/commit/cdedd5f8f920e2b933c6f915e624f5cecfa5713d
https://github.com/smurfpandey/mysqlweb/commit/ba875b6c487cd64d28ba428636e7c05ef7d67a04

**Comment by sosedoff** [comment]
Thats cool, although i just don't see an immediate need for the feature at this time. If someone really wants it  they're free to implement it and open a PR.
