### ISSUE TITLE
Bytea fields download automatically when selecting tables

### ISSUE THREAD

**Issue by benlowry** [sosedoff/pgweb#156]
If you select a table it automatically opens the rows view,  when it has bytea data pgweb downloads it all and is unresponsive till it finishes, with no notification of what's going on or how long to remain.

I think bytea fields should have a link to download, ideally with the size if that's possible.  

Second best would be a progress bar or something, that would also stop the browser messages about an unresponsive tab.

**Comment by sosedoff** [comment]
Please provide a sample SQL file so that i can test and fix the problem.

**Comment by benlowry** [comment]
create table tmp (
        blob bytea
    );
    
    insert into tmp(blob) values('\xinsert this row lots of times and pad the data with junk so it is nice and bloated asdflskadjfsaldkjfsadlkfjasdlkfjasdlfkjsadflkjsdaflksdajflasdkjfasdlkfjasdlfkjsadlfkjsadflksdajflsdkajfalsdkfjsdalkfjsadlfkjasdflkjsadflkasdjflasdkjfsdalkfjasdlkfjsdaflkjsadflksadjflkasdjflasdkfjsdalkfjsadflkjsdajlfkksjldafjasldkfjsdalfkjsadlfkjsadflkjasdflksadjflksjflksdjflskdjflsdkjflsdkfjlsdkjfsladkjfsladkfjsadlkfjsldkfjsadlfkjasdlfkjsadlfkjsdalfkjsadflksdjf')

I've been digging into the code, I don't know golang but I've managed to tentatively identify a bytea field and substitute its size, it's possible I'm not identifying it properly but maybe this gives you a head start:

    func (res *Result) PrepareBytea() {
    	for i, row := range res.Rows {
    		for j, col := range row {
			t := reflect.TypeOf(col).Kind()
			if(t != reflect.String) {
				fmt.Println("%v is not a string", t)
				continue
			}
			str := col.(string)
			if str[0] == 255 {
				fmt.Println("item is a blob", len(str), firstchar)
				res.Rows[i][j] = len(str)
			}
		}
	}
    }

**Comment by sosedoff** [comment]
Thanks, i will check on this issues once i get some free time.

**Comment by sosedoff** [comment]
I just created a table from your example using pgweb 0.9.3 (latest) on OSX (chrome) and this is what i got so far:
![screenshot 2016-07-05 18 27 59](https://cloud.githubusercontent.com/assets/71051/16603016/4cd133d2-42de-11e6-99a8-5702bbcc4bc6.png)

Nothing was downloaded automatically. Also tried Safari and Firefox, both work.
What OS and browser are you using?

**Comment by benlowry** [comment]
That is what you downloaded, you just need to provide a lot more to see the effect, try some 10s of megabytes and you will probably see your browser start straining!

**Comment by sosedoff** [comment]
Ah i see what you mean now. What is the behavior you expect?

**Comment by benlowry** [comment]
Ideally clicking the tables wouldn't include the raw data at all, that could be solved by:

- only returning the bytea data when selecting it explicitly

- a way to edit the 'you selected the table' query so you can exclude columns

**Comment by benlowry** [comment]
This was pretty much fixed for me by limiting the number of rows returned when clicking a table.

Thanks for all your wonderful work @sosedoff!
