### ISSUE TITLE
allow changing default schema via URL

### ISSUE THREAD

**Issue by CzechJiri** [sosedoff/pgweb#157]
since 9.4 postgres supports `currentSchema` via URL, it would be nice if this could be added to pgweb

```
jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema
```

**Comment by sosedoff** [comment]
Pgweb under the hood uses [lib/pq](https://github.com/lib/pq) library to connect to postgresql, please submit your request in that project.

**Comment by CzechJiri** [comment]
thank you! Opened ticket, got really quick great responses. It looks like the pq connection string supports it, they do not follow same naming as JDBC does, pq does does not use `currentSchema`, it uses `search_path` instead, the connection looks like this and works like a charm :-)

```
postgresql://localhost:5432/mydatabase?search_path=myschema
```

**Comment by tindzk** [comment]
Specifying `search_path` is possible, but in my case, pgweb opens the `public` schema in the sidebar instead of the configured schema.

**Comment by sosedoff** [comment]
I think the challenge here is to display the right option, ie we're expecting `public` to be a default search path, however, im not sure what you'd expect to see if you pass multiple schemas.

**Comment by tindzk** [comment]
If multiple search paths are specified, the corresponding schemas could be expanded in the sidebar.

Currently, the `public` schema is always expanded regardless of the `search_path` setting. In our case, all tables are in the `catalog_test` schema while the `public` schema is empty.

<img width="246" alt="image" src="https://github.com/sosedoff/pgweb/assets/196819/be3ed902-547d-44c6-92da-bdf53b500379">
