### ISSUE TITLE
sosedoff/pgweb:latest is not latest

### ISSUE THREAD

**Issue by CzechJiri** [sosedoff/pgweb#159]
sosedoff/pgweb:latest seems to be 5 months old and looking at the size, corresponds to version 0.8 instead of latest 0.9.2

https://hub.docker.com/r/sosedoff/pgweb/tags/

**Comment by sosedoff** [comment]
You're right. I think i pushed a wrong tag.

**Comment by sosedoff** [comment]
Fixed. Public registry should contain proper `latest` and `0.9.2` release rebuilt using alpine image and as a result its image side has been reduced to 8Mb.
