### ISSUE TITLE
Content tab doesn't double-quote table in query

### ISSUE THREAD

**Issue by bblack** [sosedoff/pgweb#16]
In postgres, identifiers need to be named with double-quotes if they're not all lowercase. For example, I have a table `Accounts`, and when I click the "content" tab, I see:

```
ERROR: pq: relation "account" does not exist
```

because the query issued was

```
SELECT * FROM Account LIMIT 100;
```

with `Account` not double-quoted.

**Comment by tindzk** [comment]
I noticed the same bug in the last two pgweb versions. My table is called "Client", but when I click on it in the sidebar, the "Rows" window shows the following error:

> ERROR: pq: relation "xyz.client" does not exist
