### ISSUE TITLE
Heroku deploy (with deploy button) is broken

### ISSUE THREAD

**Issue by plispe** [sosedoff/pgweb#171]
When I deploy pgweb to heroku with deploy button from github. I get following error 

Asset static/index.html can't read by error: Error reading asset static/index.html at /Users/sosedoff/go/src/github.com/sosedoff/pgweb/static/index.html: open /Users/sosedoff/go/src/github.com/sosedoff/pgweb/static/index.html: no such file or directory

I have no idea what's going on.

**Comment by sosedoff** [comment]
Fixed. I accidentally committed dev version of bindata (which is used to store all static assets).

**Comment by Wilbeibi** [comment]
Today, I saw this problem again.
I tried `brew cask install pgweb`, or `go get` and build, both method show the same error messages.
