### ISSUE TITLE
Add AUTH_USER / AUTH_PASS environment variables

### ISSUE THREAD

**Issue by felixbuenemann** [sosedoff/pgweb#178]
It would be great if AuthUser and AuthPass could be set with environment variables. This would allow to use basic auth when running with the default docker image.

**Comment by sosedoff** [comment]
Sure, i'll have a look at this

**Comment by sosedoff** [comment]
Implemented in master and will be available in the next release.

**Comment by felixbuenemann** [comment]
Thanks, I'll try it out once the new release is out and pushed to docker hub.
