### ISSUE TITLE
Linux: Wrong paths lead to asset error

### ISSUE THREAD

**Issue by numbleroot** [sosedoff/pgweb#180]
Hi Dan,

when I `go get` this project, `go build` and afterwards open up `http://localhost:8081`, I get an 400 error with following message:
`Asset static/index.html can't read by error: Error reading asset static/index.html at /Users/sosedoff/go/src/github.com/sosedoff/pgweb/static/index.html: open /Users/sosedoff/go/src/github.com/sosedoff/pgweb/static/index.html: no such file or directory`

Taken from the closed issues, I guess #171 happened again.

Also: kudos for this great project!

**Comment by sosedoff** [comment]
You're right. Fixed the issue and will probably do something about it for the long run.
