### ISSUE TITLE
Allow disabling Connect / Disconnect functions

### ISSUE THREAD

**Issue by felixbuenemann** [sosedoff/pgweb#181]
It would be great if there was a way to lock pgweb to a single database specified by the DATABASE_URL and disable the functionality to disconnect and connect to different databases.

There yould be a commandline switch like `--single-database` and an environment var like SINGLE_DATABASE=1.

**Comment by sosedoff** [comment]
What is your use case for such feature?

**Comment by felixbuenemann** [comment]
I would like to give developers access to databases for certain projects. The should not be able to connect to any other databases from pgweb.

**Comment by felixbuenemann** [comment]
To add a little more detail: The database server is running in a virtual private network and I would like to deploy one pgweb container per app I would like to give database access to with different basic auth credentials.

**Comment by syamantm** [comment]
+1

**Comment by ManuelWeiss** [comment]
+1

**Comment by sosedoff** [comment]
Implemented in master
