### ISSUE TITLE
add new row/save

### ISSUE THREAD

**Issue by jamesdixon** [sosedoff/pgweb#182]
I thought long and hard about asking this after scanning over the UI a bunch, but is it not possible to edit values directly within a row? When I click on a row, it's editable, but there's nowhere in the UI to save. I also don't see an option to insert a row in the table view. 

I know I can do both of these by executing a query, but just wanted to confirm that I'm not crazy :)

Thanks!

**Comment by sosedoff** [comment]
You're not crazy, these types of features (editing, etc) are not part of the pgweb yet. I've been experimenting with a few options but havent committed to anything just yet.

**Comment by jamesdixon** [comment]
@sosedoff - thanks, much appreciated!

Overall, loving pgweb! Appreciate your hard work.

Cheers!
