### ISSUE TITLE
Support for details of foreign tables

### ISSUE THREAD

**Issue by doomsplayer** [sosedoff/pgweb#183]
Currently pgweb won't show any information about foreign tables in left side bar.

**Comment by sosedoff** [comment]
Sorry, but this is something pgweb is not going to support at this time. I'll tag this issue so i can revisit it in the future.

**Comment by molschimke2** [comment]
What needs to be done to implement this support? Our database is heavily based on foreign tables...

**Comment by molschimke2** [comment]
In https://github.com/sosedoff/pgweb/blob/main/pkg/statements/sql/objects.sql#22, the code is explicitly not refering to foreign tables: `c.relkind IN ('r','v','m','S','s','')` - our understanding is that `c.relkind IN ('r','v','m','S','s','f')` would activate them.

Are there any other dependencies to be implemented to get foreign_tables working?
