### ISSUE TITLE
Download functionality works only once or twice.

### ISSUE THREAD

**Issue by Kiran-N** [sosedoff/pgweb#184]
I deployed pg-web in my own heroku instance. I am facing this error when I use download functionality more than twice.
{"error":"pq: syntax error at or near \"c2VsZWN0IGludm9pY2VfbnVtYmVyIGZyb20gcGF5bWVudG1hbmFnZXIuanBtX3NldHRsZW1lbnQgd2hlcmUgYmF0Y2hfaWQ9Jy0xJyBhbmQgc3RhdHVzID00MDAgb3JkZXIgYnkgc2V0dGxlbWVudF9pZCBkZXNjCgoKc2VsZWN0ICogZnJvbSBwYXltZW50bWFuYWdlci5qcG1fc2V0dGxlbWVudCB3aGVyZSBiYXRjaF9pZDw\""}

**Comment by vpsm** [comment]
Likewise.

**Comment by sosedoff** [comment]
Fixed in master and will be available in the next release.

**Comment by Kiran-N** [comment]
Thank you
