### ISSUE TITLE
Allow connecting to bookmarked server from CLI

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#189]
Something like this would work:

```
pgweb --bookmark=myserver_staging
```

**Comment by akarki15** [comment]
should the bookmark be a local file that stores db connection settings?

**Comment by akarki15** [comment]
better - where would the bookmark info be stored?

**Comment by sosedoff** [comment]
@akarki15 Server bookmarks are already implemented. This issue is about how to initialize a connection from bookmarks, which are stored under `$HOME/.pgweb/bookmarks/*.toml`

**Comment by akarki15** [comment]
i have a prototype that works. you can assign this to me
