### ISSUE TITLE
Bookmark URL Misunderstanding?

### ISSUE THREAD

**Issue by Lawrence-Baldwin** [sosedoff/pgweb#204]
Hi,

Should it be possible to connect directly to a database using the bookmark url WITHOUT having to go via the login screen? 
If so, what is the format for the full URL? For example, if I connect to pgweb with URL   http://localhost:8081/#postgres://postgres:myPwd@localhost:5432/mydb?sslmode=disable then it takes me to the normal login screen but I'm expecting it just to log straight in to the database as per the bookmark details in the URL.

Am I doing something wrong here or can bookmarks only be used be on the Scheme page?

**Comment by sosedoff** [comment]
Using latest pgweb (0.9.6) you should be able to connect to the bookmark using `-b` or `--bookmark` flag. The bookmark must be saved under `$HOME/.pgweb/bookmarks` first.

**Comment by sosedoff** [comment]
Btw, the url you provided does not work that way. If you have a few bookmarks saved, they'll be available on the login page. There's no other way to use them in the web app, only via the command line option.

**Comment by gytisgreitai** [comment]
Sorry to bump into old thread. Do I understand correctly that there is no way how to dynamically link to a connection via url? E.g. we have a lot of dynamic environments which are autogenerated and I would like to automatically create links for pgweb to autonnect

One option is to probably enable cors and do a post to /api from the web app where I want to include dynamically generated links and then redirect the user?
