### ISSUE TITLE
--lock-session doesn't work with a bookmark

### ISSUE THREAD

**Issue by kblomqvist** [sosedoff/pgweb#205]
```bash
$ ./pgweb --lock-session --bookmark=server
Please provide connection url

$ cat .pgweb/bookmarks/server.toml 
url = "postgres://postgres:postgres@localhost:5432/postgres"
```

Works without `--lock-session`.

**Comment by sosedoff** [comment]
Thanks will take a look

**Comment by kblomqvist** [comment]
There's also a `--lock-session` related question in #195. Seems like `--lock-session` works with `--url` only.

**Comment by sosedoff** [comment]
This is fixed in master. Please give it a try.

**Comment by kblomqvist** [comment]
I have never compiled before so I tried following (on Debian) and got the build error shown below.

```bash
cd workspace
git clone https://github.com/sosedoff/pgweb.git
cd pgweb
sudo apt-get install golang-go
export GOPATH=~/.gocode
export GOBIN=$GOPATH/bin
export PATH=$GOPATH:$GOBIN:$PATH
make setup
make dev

main.go:12:2: cannot find package "github.com/sosedoff/pgweb/pkg/api" in any of:
	/usr/lib/go/src/pkg/github.com/sosedoff/pgweb/pkg/api (from $GOROOT)
	/home/kiblomqv/.gocode/src/github.com/sosedoff/pgweb/pkg/api (from $GOPATH)
```

**Comment by sosedoff** [comment]
Im not sure why you're getting the error, perhaps older version of go? Anyways, to simplify testing - i attached a binary that you could try.
[pgweb_linux_amd64.zip](https://github.com/sosedoff/pgweb/files/604263/pgweb_linux_amd64.zip)

**Comment by kblomqvist** [comment]
Thanks! I got it working and the fix is working too.

Here's the instructions if somebody else is struggling with the build. Read the installation instructions from https://golang.org/doc/install. I did the following steps:

```bash
wget https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.7.3.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

mkdir -p $HOME/workspace/go
export GOROOT=$HOME/workspace/go
export GOPATH=$HOME/workspace/go
export PATH=$PATH:$GOROOT/bin

go get github.com/sosedoff/pgweb
cd workspace/go/src/github.com/sosedoff/pgweb
make setup
make dev
```
