### ISSUE TITLE
Custom Login page / Custom database list feature

### ISSUE THREAD

**Issue by adamjaso** [sosedoff/pgweb#207]
I'm adding a feature to make `pgweb` require login with Cloud Foundry. I'm also adding a feature to provide a list of available databases once the user has logged in. I've forked `pgweb` and started building the features, but I'm not quite finished yet. I understand that my use case is somewhat specific, but I wanted to ask if these features can be generalized into a form that could be admitted into the primary `pgweb` repo? Perhaps we could design some simple API that would allow other users to build additional login integrations (of which Cloud Foundry would be one), if they wanted to (which could be submitted via PR)? The same idea could apply for the list of databases provided upon login. I'm ready to help with ideas and building out this feature, but I just wanted to get feedback on how this might be best implemented. My fork is here: https://github.com/adamjaso/pgweb/tree/cflogin

**Comment by sosedoff** [comment]
Hi @adamjaso and thanks for the feedback. I've thought about some similar use case but most of those integrations are somewhat non-trivial and dont really belong in pgweb. Maybe in the next major version i will come up with plugin system but for now i dont think any of the custom stuff makes any good use for the regular users.
