### ISSUE TITLE
Current search results (in Rows tab) also shown in SQL Query tab

### ISSUE THREAD

**Issue by kblomqvist** [sosedoff/pgweb#209]
If I do search in Rows tab and switch to the SQL Query tab the current results are also shown there. However, I cannot export the results as CSV, JSON or XML. Thus would it make sense to show the current SQL query also in SQL Query tab along with the working export buttons. Otherwise reset the latest search and add export buttons also to Rows tab?

**Comment by sosedoff** [comment]
Thanks for the report, i'll fix that in the next release.
