### ISSUE TITLE
Bad connection string rewrite on DB change

### ISSUE THREAD

**Issue by fduraffourg** [sosedoff/pgweb#211]
The connection string is badly rewritten on DB change when no database was specified for the current connection:

- Connect without specifying a database name
- On the top left, change to another database
- The change fails

It appears that the connection string has a path of `/`. And the function that rewrite it will replace the first slash that follows the scheme. So we got a connection string that looks like this: ` Changed Url: postgres:/newdbname/user:pass@192.168.200.3/?sslmode=disable`

I'll submit a PR right away for this issue.

**Comment by sosedoff** [comment]
Fixed in master.
