### ISSUE TITLE
Bad display of db name when it is too long

### ISSUE THREAD

**Issue by fduraffourg** [sosedoff/pgweb#213]
When the name of the DB is too long, it doesn't display properly. Same behavior with Firefox and Chromium.

![scrsh hl1](https://cloud.githubusercontent.com/assets/220489/21811914/9732b470-d751-11e6-8921-fe96fedf3aed.png)

(Node: I selected part of the text so that you can more easily see its position)

**Comment by sosedoff** [comment]
Fixed in master. See example.
![screenshot 2017-01-10 13 45 57](https://cloud.githubusercontent.com/assets/71051/21821989/23f774fc-d73b-11e6-8524-bd8ca3339c3c.png)
