### ISSUE TITLE
Updating values from rows view?

### ISSUE THREAD

**Issue by RONNCC** [sosedoff/pgweb#215]
Is it possible to execute a SQL update query from changing the text and hitting enter or similar?

![image](https://cloud.githubusercontent.com/assets/1313566/22039808/be67d4d0-dcce-11e6-9053-c074e422a490.png)

**Comment by sosedoff** [comment]
Currently - no. Im still trying to find some time and implement row editing functionality. It should be fairly straightforward as long as you try to edit rows in the "browse" mode. Editing rows in custom query result would be complicated and does not make sense.

**Comment by Falconerd** [comment]
I would also like to see this. As pgweb is a nice looking GUI, I thought it'd be targeting users who may not necessarily know SQL.

If you could update data through the row view, then someone like an office admin could use this pretty easily.

**Comment by VaWa** [comment]
Hello dear Dan. 
First off all thank You very much for your great work. 
This project is very valuable and useful. 
I will also appreciate very much if row editing and adding functionality is implemented and this feature will bring this wonderful project to whole new level of usability for many users.
Thank you very much.

**Comment by awildeep** [comment]
@sosedoff I think I am missing something.  When:

-  I use the sidebar navigation and drill into a table (No custom query, no views)
- Then I double click a row that has a value
- I see a textarea box which allows me to change the value
- However I see no way to save my change and issue the update

I am assuming this is what you mean by "Currently - no. Im still trying to find some time and implement row editing functionality."?

Using Chrome [58.0.3029.96 (64-bit)] on OSX [10.11.6 (15G1421)]

**Comment by sosedoff** [comment]
Thats correct, row editing is not supported in any form in pgweb at the moment. Textbox is meant to easily copy cell's data.

**Comment by cheungpat** [comment]
Hi @sosedoff, I need this for some of my projects. Can I work on this? I intend to extend the API to support insert/update/delete and update the UI to support modifying data.

**Comment by jdalrymple** [comment]
@cheungpat Any chance you got around to adding editting functionality?

**Comment by MostHated** [comment]
Man, the whole reason I was excited to use this was that I figured you could edit the data. Surprised that is not the case.

**Comment by jdalrymple** [comment]
lol its still a wicked app, just missing some functionality. Id make a PR but id have to really dig into it to understand it all

**Comment by joekohlsdorf** [comment]
Could we at least make the fields not change into an editable text box while this function isn't implemented? I have users coming to my desk confused all the time.

**Comment by RONNCC** [comment]
+1 readonly field

**Comment by Vincent14** [comment]
Agree with @joekohlsdorf I spent time on Google to find what I did wrong before reading this thread and understand I won't succeed in.

**Comment by joekohlsdorf** [comment]
Got annoyed by this again today. The change is simple, in this line:
https://github.com/sosedoff/pgweb/blob/15c21b63793d5b8e6de252a76902fc09ff87f7cf/static/js/app.js#L1124
Change `<textarea />` to `<textarea readonly />`.

**Comment by OmgImAlexis** [comment]
I know +1s don't help but can this please be fixed, even the `readonly` option would help.

**Comment by sosedoff** [comment]
Inline textareas have been completely removed from pgweb in the latest release. 
It's no longer needed since there's a context menu to copy the contents of the cell (right click).

**Comment by sebolio** [comment]
3 years later, still can't edit data in a row? 🤪

**Comment by Vincent14** [comment]
You can with PgAdmin...

**Comment by younishd** [comment]
+1 for this feature. Unfortunately, was a deal-breaker for us.

**Comment by sosedoff** [comment]
I think it was a default action when closing, so i probably didn't pay attention (this was 6 years ago!). As for the reason, row editing was never a goal of this project, there are better tools for data editing out there (pgAdmin is an example).
