### ISSUE TITLE
Error: dial tcp: no suitable address found

### ISSUE THREAD

**Issue by monaka** [sosedoff/pgweb#220]
I got the error `Error: dial tcp: no suitable address found` when I make Pgweb (v0.9.6) booting with `DATABASE_URL`.
After changing its hostname to IP address, it runs with no error.

Referring to some another projects, this error is caused by Go 1.7.0 and it may be fixed by building with Go 1.7.1.
E.g: https://github.com/golang/go/issues/16739

**Comment by sosedoff** [comment]
This should be fixed as i've switched master to use go 1.7.5.
