### ISSUE TITLE
pgweb linux installation issue

### ISSUE THREAD

**Issue by gouri87** [sosedoff/pgweb#221]
#### Description of issue
I have tried to install pgweb on Ubuntu 14.04.5 LTS and I have been unsuccessful so far. I am following the wiki page for – Installation as well as tried Build from source. I have constantly been getting errors. I have linuxbrew installed. 
With just the basic installation - I get stuck at the very last step  - brew cask install pgweb - error - Verifying checksum for Cask pgweb
Error: No such file or directory - /usr/bin/hdiutil. 
With the Build from source - make setup runs but tells me that I am not in the GOPATH (which doesn't have the makefile) and make dev doesn't run because it cannot find the -$HOME/.linuxbrew/Cellar/go/1.7.5/libexec/src/github.com/sosedoff/pgweb/pkg/command (from $GOROOT)
$GOPATH/src/github.com/sosedoff/pgweb/pkg/command

**Comment by sosedoff** [comment]
Hi,

I think all those issues really have nothing to do with pgweb for a few reasons:
- pgweb project has not been tested to work with linuxbrew so i cant really tell if its homebrew issue or something else. osx is supported. 
- when installing from source you must set your GOROOT and GOPATH correctly for the build to work. 

Alternatively you can always download a prebuilt binary file for your OS: https://github.com/sosedoff/pgweb/releases/download/v0.9.6/pgweb_linux_amd64.zip

**Comment by TomoGlavas** [comment]
A short how to or link to how to install would be nice.
Having problems getting the right binary and method for installing on Ubuntu.

**Comment by sosedoff** [comment]
@TomoGlavas check https://github.com/sosedoff/pgweb/wiki/Installation
