### ISSUE TITLE
Error: pq: schema "dbms_rls" does not exist

### ISSUE THREAD

**Issue by zoujd-github** [sosedoff/pgweb#222]
[root]# /opt/go/pgweb  --url postgres://test:test@10.88.0.1:5444/ptgbdb?sslmode=disable 
Pgweb v0.9.6
Connecting to server...
Checking database objects...
Error: pq: schema "dbms_rls" does not exist

**Comment by zoujd-github** [comment]
pgweb start error

**Comment by zoujd-github** [comment]
but this schema "dbms_rls" is exist,wy?
![image](https://cloud.githubusercontent.com/assets/19323469/22968928/71aa1046-f3a7-11e6-849c-89d56da6365f.png)

**Comment by sosedoff** [comment]
Are you using the same user for pgweb and your other db tool? I might suspect it has something to do with permissions.

**Comment by sosedoff** [comment]
@zoujd-github ping, care to provide more details? otherwise i will close this issue since i don't have any way to reproduce the problem.

**Comment by sosedoff** [comment]
Closing due to no response.
