### ISSUE TITLE
Add a disk-backed custom query log

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#226]
Storing SQL query log (user-generated) into a file would be a good solution for history persistence. Something like `$HOME/.pgweb/history.json` is fine, although will probably break when running multiple instances of pgweb on the same machine.

**Comment by sosedoff** [comment]
Possible alternative: local SQLite3 db.

**Comment by akarki15** [comment]
Are you thinking persisting every single query in this log? or would there be a customs store query option?

Another question - how would we uniquely identify clients? Say one client saves the query, quits and comes back up. How would we identify that the new client is the same one that stored the query?

**Comment by sosedoff** [comment]
This issue is too old and never got any traction, closing.
