### ISSUE TITLE
Generate charts

### ISSUE THREAD

**Issue by mytototo** [sosedoff/pgweb#229]
Hey,

Do you have plans about generating charts from a query's result?
Like Hue for example.

Thanks.

**Comment by sosedoff** [comment]
Not at the moment, but i thought about adding a very basic charting feature in the past.

**Comment by mytototo** [comment]
I think it should be great to have this kind of feature even it's really basic. If people want more they always are able to customize it (and make a PR).

**Comment by sosedoff** [comment]
Im going to keep the issue open in case i have time to work on it or someone else decides to contribute.
