### ISSUE TITLE
Blank Page on IE

### ISSUE THREAD

**Issue by ppyang** [sosedoff/pgweb#231]
Cannot open the webpage in IE. It only shows a blank page. 

Company PC only has IE 11.  Cannot install other browser.

![pgweb-ie](https://cloud.githubusercontent.com/assets/838759/24423287/7276dfe8-13ca-11e7-9a85-7b9bd2c1bdbe.jpg)

**Comment by sosedoff** [comment]
Damn IE, i'll take a look.

**Comment by sosedoff** [comment]
Issue: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/of
`for x of array` is not supported in IE11.
