### ISSUE TITLE
Activity Tab only shows ERROR: pq: column "waiting" does not exist.

### ISSUE THREAD

**Issue by MahatmaFatalError** [sosedoff/pgweb#233]
On PostgreSQL 9.6.2 on x86_64-pc-mingw64

![image](https://cloud.githubusercontent.com/assets/776825/25483737/644c8798-2b57-11e7-89e9-8427a58dc28f.png)

**Comment by sosedoff** [comment]
Yeah, its a known issue. `waiting` is not available in `pg_stat_activity`. I haven't had time to fix this.

**Comment by bjeanes** [comment]
Here's the fix for this in a similar query: https://github.com/demikl/pg_activity/commit/10cfc484b87e3ad018b9d6048954ff85f58ae904

Might be useful for anybody wishing to address this before @sosedoff can...

**Comment by sosedoff** [comment]
@bjeanes thanks, i'll check it out.

**Comment by sosedoff** [comment]
Should be fixed in master now.
