### ISSUE TITLE
Suggestion: Replace Bootstrap with Semantic ui

### ISSUE THREAD

**Issue by ansarizafar** [sosedoff/pgweb#236]
[Semantic UI - User Interface is the language of the web](https://semantic-ui.com) is a much better and simple ui framework. Please consider replacing Bootstrap with Sematic UI for better looking UI. If you are interested in making this change then I can also help.

**Comment by sosedoff** [comment]
How exactly the semantic UI would benefit pgweb at this time? And whats wrong with using bootstrap?

**Comment by sosedoff** [comment]
No response, closing.
