### ISSUE TITLE
DB dump support

### ISSUE THREAD

**Issue by tistvan** [sosedoff/pgweb#242]
Hello,

Ability to create SQL dumps from databases would be very useful. I was using phppgadmin before and this is the only feature I am missing from pgweb.

Thanks,
István

**Comment by sosedoff** [comment]
I don't think pgweb is a good tool to do database dumps with, `pg_dump` has been around for years and has all the options you need, although i can probably agree with you that having a very basic "db clone" feature could be useful. Under the hood it would still use `pg_dump` though, and might as well work on windows too.

**Comment by tistvan** [comment]
Yes, you are right. The reason behind this ticket is I would like to create sql dumps from Postgresql databases with a web UI and without ssh access. :)

**Comment by sosedoff** [comment]
@tistvan btw, this is doable, i was playing around with this feature today. however it will only work 100% if you have pg_dump installed on your system. So in other words, there's no way to package pg_dump with pgweb.

**Comment by sosedoff** [comment]
Work is done here #270

**Comment by tistvan** [comment]
I never said I needed pg_dump inside pgweb package :) . I just said it would be nice to create SQL dumps using pgweb. It doesn't matter if it is done using pg_dump or not. I just want to create SQL dumps from a web UI. :)
Anyway I am closing this issue because it is done in #270 .

**Comment by tistvan** [comment]
And thanks for this feature :)
