### ISSUE TITLE
List of functions in the left control panel alongside Tables, Views, etc

### ISSUE THREAD

**Issue by maksm90** [sosedoff/pgweb#250]
Hi!

Now it's impossible to see the list of functions (stored procedures) belonging to the scheme. In perspective I would like not only to see the body of function but to store its updated version (CREATE OR REPLACE FUNCTION query)

**Comment by sosedoff** [comment]
List of functions could be added, but i'm not sure about function editor. You can always use custom sql query tab for that. Pgweb does not really have any way to modify any database stuff (except for the query tab) at the moment.

**Comment by maksm90** [comment]
> List of functions could be added, but i'm not sure about function editor. You can always use custom sql query tab for that

Yes, sql query tab is intended for editing any queries including function body. But it would be nice to see the list of functions on left panel and have some tabs describing properties of selected function.

**Comment by suryapratap** [comment]
it would be really nice to atleast see function / procedure on the left panel and on selection show readonly code in structure tab.

A button to transfer the content as an alter / drop create statement to the editor tab will be icing on cake :)

**Comment by sosedoff** [comment]
Implemented in #608, with read-only capability. Dont think its a good idea to allow users to edit functions as none of pgweb's functionality allows any edits.
