### ISSUE TITLE
How to compile HTML and other static files

### ISSUE THREAD

**Issue by IIInsomnia** [sosedoff/pgweb#252]

**Comment by llitfkitfk** [comment]
https://github.com/jteeuwen/go-bindata

**Comment by sosedoff** [comment]
In regards to this project, there are two make tasks available to compile assets:

- `make dev` (will build assets that are auto-loaded from the dist on every page serve)
- `make assets` (will build assets that are served from the app itself and not from the disk).

Check `Makefile` for more details.
And yes, as previously mentioned, assets are built with go-bindata package.
