### ISSUE TITLE
Allow searching for a database via autocomplete textbox

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#253]
Currently there's no way to find a specific database when you click on the database switcher in the sidebar. If you have a lot of local databases the list becomes pretty long and unusable. 

New feature: when i click on the database name it should open up a modal with the text input. Then i can type a partial name and see autocomplete results. This is similar to OSX finder feature / alfred app.

**Comment by Vonatzki** [comment]
This is a very nice feature to have :)

**Comment by EyesBear** [comment]
I am interested in working on this. :)

**Comment by EyesBear** [comment]
For autocomplete, is there a preference on whether to utilize a third party library or not?

**Comment by sosedoff** [comment]
Third-party lib is fine as long as it does not pull the whole jQuery-UI stuff in.

**Comment by sosedoff** [comment]
Closing this since the feature has been implemented.
