### ISSUE TITLE
Not all schemas are showing

### ISSUE THREAD

**Issue by Vonatzki** [sosedoff/pgweb#257]
I'm wondering what pgweb does/checks in order for it to show user-defined schemas on the left pane.

Because right now, only the 'public' schema is showing in one of my databases when in fact I have four defined schemas in there with labels as follows: 

- agg_daily
- agg_monthly
- main_daily
- main_monthly

Do note that these schemas only contain Views as of the moment.

**Comment by sosedoff** [comment]
@Vonatzki which pgweb version are you using? Also could you provide the output (redacted if needed) of `http://localhost:8081/api/objects` ?

**Comment by Vonatzki** [comment]
I'm not quite sure if I followed your instructions to a tee.

Going to that link churns out `{"error":"Session ID is required"}`.

I have two databases in my postgresql right now. The other one has its schemas showing up on pgweb just fine.

**Comment by sosedoff** [comment]
You need to start pgweb is a single session mode, connect to you db and visit the link i provided earlier.

**Comment by Vonatzki** [comment]
Logging in to the problematic DB and accessing the link, it churns out an empty JSON `{}`.

Logging in to my other DB and using the link, it churned out JSON containing schemas and the database objects therein.

Again, the main difference of the two DBs is that the problematic one doesn't have any Table objects in its schemas, only Views.

**Comment by sosedoff** [comment]
Ok i will have to reproduce this issue locally.

**Comment by Vonatzki** [comment]
Thanks! The app looks promising and I like it that it's only an executable with no dependencies (Is this the Go magic people are raving about?)

I'd help you on the technicals but I don't know Go. I'll certainly learn more about in the future :)

**Comment by sosedoff** [comment]
@Vonatzki if its possible for you to send me the test dataset (raw sql dump) i'd fix it faster. My email is in my profile.

**Comment by sosedoff** [comment]
On the other hand, if you dont see the schema on the sidebar, there's a chance that it does not have any objects (tables/views/etc). I created an example schema with a single table in it and i could verify it shows up on the sidebar: https://www.dropbox.com/s/dl0jt9gghpx1g5h/Screenshot%202017-09-14%2000.10.15.png?dl=0
Same goes for the views / etc. See my previous comment: i will need a sample sql dump to reproduce your issue.

**Comment by Vonatzki** [comment]
> Same goes for the views / etc. See my previous comment: i will need a sample sql dump to reproduce your issue.

Apologies for not making a prompt response on this issue.

Copy, will make an anonymized SQL dump of the problematic DB. I really think it has something to do with schemas exclusively containing foreign-wrapped Views only.

**Comment by sosedoff** [comment]
@Vonatzki can we get this wrapped up? I don't really have anything to work with to reproduce your issue, so please send some example sql data, OR close the issue if it's no longer the case.

**Comment by Vonatzki** [comment]
Hi @sosedoff, will close this issue for now. The issue still remains though but I don't have time to recreate an anonymized version of the said issue for you. Apologies.

If you have time, the tables were created with the same process like the one in this link when creating the foreign data wrapped tables: 

https://robots.thoughtbot.com/postgres-foreign-data-wrapper
