### ISSUE TITLE
Browse through to record referenced by foreign key [new-feature]

### ISSUE THREAD

**Issue by beedawg1985** [sosedoff/pgweb#260]
This is a nice feature of _DB Browser_ for SQLite databases. You can cmd / ctrl + click on a referenced foreign key and you are taken to that record in the referenced table. See: https://github.com/sqlitebrowser/sqlitebrowser/issues/192

**Comment by sosedoff** [comment]
I personally don't have a specific need for this feature as i've always written a custom query to get the exact records i need, but if you have a strong use for this - feel free to submit some code that i can use to implement this. Does not have to be perfect, but if it works that's a good start.

**Comment by sosedoff** [comment]
@varp another feature you could work on.

**Comment by arteniioleg** [comment]
Feedback: I like pgweb modern design, but adminer is more feature rich, for example foreign key management. pgweb looks nice but it's good only for data browsing.

**Comment by varp** [comment]
@sosedoff you didn't accept previous ones
