### ISSUE TITLE
 pq: unknown function: has_schema_privilege()

### ISSUE THREAD

**Issue by qiangmzsx** [sosedoff/pgweb#261]
ENV:
Linux cp01-mms-feed-ting 3.10.0_1-0-0-8 #1 SMP Thu Mar 24 15:26:50 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

Pgweb v0.9.8 (git: 5e748d0cefd7063802c6433a1cfcfe467b986352)
Connecting to server...
Checking database objects...
Error: pq: unknown function: has_schema_privilege()

**Comment by sosedoff** [comment]
Which postgresql version are you running ?

**Comment by sosedoff** [comment]
Im closing this issue due to no debug information. I'd need extra info on db/permissions to troubleshoot this issue.
