### ISSUE TITLE
Add ability to import data from CSV file

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#281]
There should be some way to import data from CSV files. It would create a new table and insert all the records from a single file.

**Comment by icalF** [comment]
I'm interested to help with this. Then, how could we determine type of the column?

**Comment by sosedoff** [comment]
I dont think we need to determine the type, just insert everything as a varchar/text.

**Comment by icalF** [comment]
Nice. Will work on it ASAP

**Comment by sosedoff** [comment]
No, this features feels a bit outside of core responsibility for pgweb

**Comment by atom36942123** [comment]
Ok. 
But one thing...pgweb is one of the best open-source tools I am using. Thanks, mate

**Comment by sosedoff** [comment]
Yea i understand your point of view, but pgweb is mostly for exploring data, hence there's not even a way to edit rows. 
Maybe v1 will have that some day.

**Comment by atom36942123** [comment]
got it
