### ISSUE TITLE
Make idle connection timeout configurable

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#282]
Currently we have the inactive timeout value hardcoded in the code, see: https://github.com/sosedoff/pgweb/blob/b6167ce422ee26113222503df60932adc2736ba2/pkg/client/client.go#L369
This should be configurable using 2 new cli options:

- `--disable-connection-idle-timeout` - Turn off the feature
- `--idle-timeout` - Set the timeout value

**Comment by BharatKalluri** [comment]
Can I take this?

**Comment by sosedoff** [comment]
Go for it!

**Comment by BharatKalluri** [comment]
I am sorry, but I am not able to figure out how I should fix this. Any help?

**Comment by sosedoff** [comment]
If you still want to implement this feature, here's a few things to do:

- add cli option `--idle-timeout` (int) to specify maximum connection idle time in minutes, default to 3 hours (180 mins)
- add option `--disable-connection-idle-timeout` (bool) to disable the timeout feature altogether
- adjust the logic in the session cleanup worker here: https://github.com/sosedoff/pgweb/blob/master/pkg/api/session_cleanup.go

**Comment by ldinc** [comment]
Is fixing client.IsIdle() func up to using with 2 new clli flags enough?
Or i missunderstood session cleanup worker?

**Comment by sosedoff** [comment]
Yeah, 2 new flags should control how the cleanup worker terminates idle connection. If we have `--disable-connection-idle-timeout` set to false we should just turn off the worker here https://github.com/sosedoff/pgweb/blob/master/pkg/cli/cli.go#L201

**Comment by ldinc** [comment]
https://github.com/ldinc/pgweb/commit/3067b06bf6e8b7f0efd6849983bd4205ddb48915
Or better change timeout minutes from float64 to int?

**Comment by sosedoff** [comment]
This has been implemented via the following flags:

```
--no-idle-timeout  Disable connection idle timeout (false)
--idle-timeout=    Set connection idle timeout in minutes (180)
```
