### ISSUE TITLE
Issue with building assets

### ISSUE THREAD

**Issue by EyesBear** [sosedoff/pgweb#284]
After I ran `make setup`, I tried to make a few small changes in `app.js` and `index.html` under `static/` and built them with `make dev`. However the changes won't show when I ran `./pgweb`. Did I missed any steps?

**Comment by sosedoff** [comment]
Hm, that should be the only step needed for the local dev. Did you try flushing your browser cache?
Also, how did you setup the project?

**Comment by EyesBear** [comment]
I tried to ran it on Safari instead of Chrome and still can't see any changes.
I cloned the repo under `$GOPATH/src/`, and `git diff` shows that `pkg/data/bindata.go` is modified.

**Comment by sosedoff** [comment]
Ah you probably cloned it under your own namespace in $GOPATH/src, you'll need to clone it as `$GOPATH/src/github.com/sosedoff/pgweb` so that all package references could stay the same.

**Comment by EyesBear** [comment]
Thanks!
