### ISSUE TITLE
Add SQL keyword autocompletion

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#285]
This is another feature that i wanted to add for years but never had time for. Basically, when you type any SQL statements or functions the UI should be able to find a suggestion, like `SELECT`, `FROM`, `ORDER` etc. Ace editor seems to support that.

**Comment by cristianoliveira** [comment]
Hey @sosedoff I will try to do it! I've been using the pgweb and I think it would might be easy :)

**Comment by sosedoff** [comment]
@cristianoliveira have you made any progress on this feature?

**Comment by Vonatzki** [comment]
This feature will be a heaven-sent for those who manages hundreds of tables in their database like me :)

**Comment by sosedoff** [comment]
Keyword and object autocompletion is in master now
