### ISSUE TITLE
Sort rows in a table by clicking on a column header ( set cursor: pointer )

### ISSUE THREAD

**Issue by varp** [sosedoff/pgweb#288]

**Comment by sosedoff** [comment]
I believe this is already done in #268

**Comment by varp** [comment]
Sorry, but in #268 announcements there nothing about rows sorting

**Comment by sosedoff** [comment]
Row sorting was implemented a while ago. I was referring to the "cursor: pointer" change made in the linked PR.

**Comment by varp** [comment]
Ohh, I understood
