### ISSUE TITLE
Add ability to copy table name from the sidebar

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#301]
It would be nice to be able to copy the (selected) table name from the sidebar. We currently have ability to copy table column names, you right click on the column and select "Copy column name". Same functionality should also work for table names.

**Comment by ldinc** [comment]
Hi, shoud it be copied to clipboard from "data-id" value or value from <i>...</i>?

**Comment by sosedoff** [comment]
Yeah, copied from `data-id`, but without the namespace `public.mytable` -> `mytable`

**Comment by sosedoff** [comment]
Ok, this is available in master now, closing.
