### ISSUE TITLE
exporting Tables with uppercase letters

### ISSUE THREAD

**Issue by alfozan** [sosedoff/pgweb#310]
There is a table `Languages` in the scheme `public`; attempting to export it (i.e. to `JSON`) by right clicking on the table name fails and shows an error message.

**Expected:**
`JSON file
`
**Error message result:**
`{"error":"pq: relation \"public.languages\" does not exist"}
`
**Note:**
the query below works:
`select * from public."Languages"
`
This issue might be related to [https://github.com/sosedoff/pgweb/issues/21](url)

**Comment by sosedoff** [comment]
Uh, i'll check on this one. I thought it was already fixed.

**Comment by transcranial** [comment]
Same issue, occurs with trying to show the "Structure" tab for a table containing uppercase letters as well:

`ERROR: pq: relation "public.exampletable" does not exist`, for `exampleTable`

**Comment by kevflynn** [comment]
I believe the same issue occurs when trying to add query constraints for columns with uppercase letters - i.e. select * from table where columnName = 'test'
ERROR: pq: column "columnNmae" does not exist

**Comment by alfozan** [comment]
@transcranial : try `public."exampletable"`  instead of `"public.exampletable"`

@sosedoff : any plans to fix this in the upcoming release?
Thank you

**Comment by sosedoff** [comment]
Looks like it has been fixed in 0.10.0
