### ISSUE TITLE
"Asset static/index.html can't read by error" failed again

### ISSUE THREAD

**Issue by Wilbeibi** [sosedoff/pgweb#314]
Hi Dan,
I saw "Asset static/index.html can't read by error: Error reading asset static/index.html at /Users/sosedoff/go/src/github.com/sosedoff/pgweb/static/index.html: open /Users/sosedoff/go/src/github.com/sosedoff/pgweb/static/index.html: no such file or directory"

after `brew cast install pgweb` or `go get` and build from source code.
This is the same issue as [#180](https://github.com/sosedoff/pgweb/issues/180), [#171](https://github.com/sosedoff/pgweb/issues/171) and [#86](https://github.com/sosedoff/pgweb/issues/86).

Then I tried `git checkout v0.9.8` then build, it works fine.

How about add this check to CI ?

Thank you for your work, it's a pretty nice tool.

**Comment by sosedoff** [comment]
@Wilbeibi i've added guard to CI recently. Although all the releases pushed out to github should not be affected. Which pgweb versions that you've tried had this asset bug ?

**Comment by Wilbeibi** [comment]
@sosedoff 0.9.9

**Comment by sosedoff** [comment]
0.9.9 binary release and source code does not contain any dev assets, i'm not sure how you ended up with the version that does. if you know the git sha i can check if it's broken.

**Comment by Wilbeibi** [comment]
Oh, sorry, thank you for the suggestions. 

After `git pull` I get the latest version and it's working now (weird, why `go get` does not give me the right one?). And the `brew cask` issue is because my environment PATH found the `go get` one first.

Thanks again for your work.

**Comment by sosedoff** [comment]
If you're building from master - then yes, assets get broken sometimes, that explains why you were seeing the error.
