### ISSUE TITLE
[feature] backup and restore

### ISSUE THREAD

**Issue by u007** [sosedoff/pgweb#336]
hi,

how about backup and restore?

**Comment by sosedoff** [comment]
pgweb is a database browser tool so backup and restore functionality is really out of scope. use `pg_dump` / `pg_restore` commands. pgweb however offers a pretty simple way to export the database as a sql.gz dump without any options, and that's pretty much it.

**Comment by cachho** [comment]
> pgweb however offers a pretty simple way to export the database as a sql.gz dump without any options, and that's pretty much it.

@sosedoff where can I do this?
