### ISSUE TITLE
Preserve table sorting when switching between tables

### ISSUE THREAD

**Issue by beedawg1985** [sosedoff/pgweb#344]
Sure there'll be several schools of thought on this but I frequently will sort a table by a field, check a row, then browse to another table to cross-reference something, before browsing back to the original table.

When I do this the original table has re-sorted itself back to default. Wondering if it would make sense to keep table sorting (and possibly highlighting of rows, editable text boxes etc.) preserved until a user deliberately refreshes or resets a table?

**Comment by sosedoff** [comment]
We can save the table filters and sorting state and restore it when switching between tables. I'll see what i can do here.

**Comment by sosedoff** [comment]
Im closing for now as preserving the sorting when switching tables is not a consistent UX.
