### ISSUE TITLE
password with '#' in url doesnt work

### ISSUE THREAD

**Issue by MstWntd** [sosedoff/pgweb#349]
Issue:
using '#' in the password field of the URL causes pgweb to not connect.
'#' works when used in the "standard" connection method.

Bad Example:
postgres://pguser:pgpass###@localhost:5433/mydb?sslmode=disable <-- this causes pgweb to get confused as to where the host/port is in the url

Good Example:
postgres://pguser:pgpass@localhost:5433/mydb?sslmode=disable <--- this works

![image](https://user-images.githubusercontent.com/3737664/37153627-3d14b4a4-22d5-11e8-97a1-87512baa6207.png)

![image](https://user-images.githubusercontent.com/3737664/37153732-a17e625a-22d5-11e8-93bd-9e4ca1ebfea1.png)

Pgweb v0.9.11 (git: c32784e8aebec35c1f68e11bc004f45dedbda283)

**Comment by sosedoff** [comment]
Ah, the `#` sign must be escaped for this to work, ie `postgresql://user:%23password%23@hostname/database`

**Comment by MstWntd** [comment]
Yup that worked!.. btw you have amazing project here and i really appreciate it!

**Comment by sosedoff** [comment]
👍
