### ISSUE TITLE
[Feature] Responsive CSS for mobile view

### ISSUE THREAD

**Issue by MstWntd** [sosedoff/pgweb#350]
Would nice to have a more of a "mobile feel" when using pgweb via a mobile browser.

**Comment by sosedoff** [comment]
Mobile devices were never meant to be supported by pgweb, and there's no plan on supporting in the the current version.

**Comment by AlmogBaku** [comment]
Hey,
@sosedoff, although it wasn't meant to be supported, I suggest we'll keep this issue open.

**Comment by AlmogBaku** [comment]
cc @sosedoff

**Comment by sosedoff** [comment]
are you asking me to implement all these mobile changes or are you going to take a lead on it?
