### ISSUE TITLE
Display table and column list based on first few typed chars

### ISSUE THREAD

**Issue by debashree-patnaik** [sosedoff/pgweb#352]
While writing queries, I see that the table or column names are not shown for the user to select based on the first few typed characters.

It would definitely help to have this feature in reducing the time while writing queries.

**Comment by sosedoff** [comment]
This could be added on top of #285, but yeah the keyword/db objects autocompletion is something that i've been meaning to implement for a long time now. Hopefully i get to it when i get a bit more of free time.

**Comment by sosedoff** [comment]
I think we can close this since basic database objects autocompletion is done.
