### ISSUE TITLE
[How to] ldap connectivity

### ISSUE THREAD

**Issue by MstWntd** [sosedoff/pgweb#353]
I would like to hook this up to ldap instead of having its basic auth in place.

is this possible by using apache somehow or use the backend connectivity feature?..

**Comment by sosedoff** [comment]
You can try putting https://github.com/gopenguin/ldap-proxy in front of pgweb, i haven't tried that thought. Maybe in future pgweb can offer native LDAP authentication backend, but there's not much need for it at the moment.
