### ISSUE TITLE
Option to not show connection details

### ISSUE THREAD

**Issue by MstWntd** [sosedoff/pgweb#354]
When using bookmarks, there should be a cli option to hide the connection details from the users.

**Comment by sosedoff** [comment]
Sorry i forgot to reply in time. Can you clarify on why the connection details should not be visible if bookmark is being used? No sensitive information is exposed on that page, and any user can actually get the same info by running a sql query themselves.

**Comment by sosedoff** [comment]
No feedback, closing for now. I dont think hiding any connection details would make any sense, see my previous post in this thread.
