### ISSUE TITLE
Add transaction support

### ISSUE THREAD

**Issue by aksdb** [sosedoff/pgweb#355]
It would be nice for pgweb to support transactions and allow to toggle between auto-commit and manual begin/commit/rollback. That way you could perform a series of manipulations, check the result and commit only if you are satisfied.

**Comment by sosedoff** [comment]
Are you talking about the SQL query pane?

**Comment by aksdb** [comment]
For now - since this is the only place where I can manipulate data.
If pgweb gets form / table based editing support sometime in the future, that would be a good candidate for transactions as well.

**Comment by sosedoff** [comment]
Closing this for now, there's no plan for transactional support for the time being.
