### ISSUE TITLE
[0.9.12] Connect to fresh CockroachDB: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tomholub** [sosedoff/pgweb#361]
Managed to successfully connect to local CockroachDB, and I can issue SQL statements and get back results.

The node has no databases yet.

Error:
```
app.js:126 Uncaught TypeError: Cannot read property 'length' of undefined
    at app.js:126
    at Array.forEach (<anonymous>)
    at buildSchemaSection (app.js:121)
    at app.js:157
    at Object.error (app.js:76)
    at j (jquery.js:2)
    at Object.fireWith [as rejectWith] (jquery.js:2)
    at x (jquery.js:4)
    at XMLHttpRequest.<anonymous> (jquery.js:4)
```

![image](https://user-images.githubusercontent.com/6306961/40413214-da750cae-5ea7-11e8-9f6c-1f317aaf2b36.png)

**Comment by tomholub** [comment]
Once I issue the following statement & refresh the page, error goes away:
```sql
SET database = db_name;
```
Ideally, the app would work properly w/o a DB selected.

**Comment by sosedoff** [comment]
Fix has been added to master. However, the app will require the user to specify the database name, because a lot of endpoints expect the "correct" environment, ie. postgres will try to use the current username as a database (and fail if it does not exist), but that's not the case with cockroach.
