### ISSUE TITLE
How to disable full table count on rows tab

### ISSUE THREAD

**Issue by mbande** [sosedoff/pgweb#364]
when a user clicks on table names, the ```rows``` tab is activated, and it triggers a full table count query.
in my case, tables have many many rows, and [slow counting](https://wiki.postgresql.org/wiki/Slow_Counting) problem appears.
is there any way to disable full page count? or use some king of [count estimate](https://wiki.postgresql.org/wiki/Count_estimate)?

**Comment by sosedoff** [comment]
There's no way to disable the pagination (which uses count(1)) at this time. I don't think i would have any time to get this issue resolved, unfortunately. I'd rewrite a lot of backend code to get everything smooth, but that's a completely new time sucker.

**Comment by jimis** [comment]
In my case, the statement `SELECT COUNT(1) FROM ...` is the only slowdown when paginating through a 200 Mrows long VIEW. The server is 100% I/O bound. On the contrary, just SELECT'ing the view using `psql` is instantaneous.

I was ready to open a new issue, but maybe we should just reopen this one.

**Comment by jimis** [comment]
Submitted https://github.com/sosedoff/pgweb/issues/661
