### ISSUE TITLE
When running a windows client using SSL there are some commands not recognised?

### ISSUE THREAD

**Issue by natiki** [sosedoff/pgweb#371]
Hi,

I am trying to get this working under Windows 10 using SSL. However when I make a connection I get:

```
'sslkey' is not recognized as an internal or external command,
'sslmode' is not recognized as an internal or external command,
'sslrootcert' is not recognized as an internal or external command,
```

On a Windows system where do I get those binaries?

**Comment by sosedoff** [comment]
How are you connecting to the postgres server?

**Comment by natiki** [comment]
I have spun up a local development cluster of CockroachDB using the secure mode by following the instructions found at https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html

This talks PostgreSQL on the wire and according to a Cockroach forum post people have had success using pgweb to connect to it.

So according to the primary node my connection string is:
```
postgresql://root@localhost:26257?sslcert=certs%5Cclient.root.crt&sslkey=certs%5Cclient.root.key&sslmode=verify-full&sslrootcert=certs%5Cca.crt
```
So I attempt to call that as follows:

![image](https://user-images.githubusercontent.com/4738140/44458662-4201b900-a64a-11e8-8746-a66efd2bcbcb.png)

**Comment by natiki** [comment]
OK we are getting somewhere - double quotes is what is needed:

```
C:\CockroachDB>pgweb --url 'postgresql://root@localhost:26257?sslcert=certs%5Cclient.root.crt&sslkey=certs%5Cclient.root.key&sslmode=verify-full&sslrootcert=certs%5Cca.crt'
Pgweb v0.9.12 (git: 9af721176bf7b41366f0de8251fff0b47da8fce3)
Error: Invalid URL. Valid format: postgres://user:password@host:port/db?sslmode=mode
'sslkey' is not recognized as an internal or external command,
operable program or batch file.
'sslmode' is not recognized as an internal or external command,
operable program or batch file.
'sslrootcert' is not recognized as an internal or external command,
operable program or batch file.

C:\CockroachDB>pgweb --url "postgresql://root@localhost:26257?sslcert=certs%5Cclient.root.crt&sslkey=certs%5Cclient.root.key&sslmode=verify-full&sslrootcert=certs%5Cca.crt"
Pgweb v0.9.12 (git: 9af721176bf7b41366f0de8251fff0b47da8fce3)
Connecting to server...
Error: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less.
```

So as this is a windows machine I am not sure how you would like the permissions to avoid the `0600` error?

**Comment by sosedoff** [comment]
0600 is not an error, its the required permissions mode on those certs. most likely you have too open permissions right now, so try changing that first. you're almost there.

**Comment by natiki** [comment]
I understand it is a permissions issue. However this is a Windows system so what are you expecting the permissions to be on Windows?

**Comment by sosedoff** [comment]
I dont know, the error is coming from the pgweb's dependency (postgres driver) so you'd have to research on the required permissions level. For the reference: https://github.com/lib/pq/issues/489

**Comment by sosedoff** [comment]
Any luck getting everything running properly?

**Comment by natiki** [comment]
Not as of yet. Basically even if I set the files to read only on Windows then it is still not happy. I tried same as the original reporter some other restrictions on the permissions of the files with no joy either.  According to that issue it appears that the fix is in to work around this in pq. Is it possible that pgweb / pg don't know what OS they are running on?

**Comment by cbandy** [comment]
Godeps is pinned to a lib/pq version from ~3 years ago. The fix for Windows permissions was merged ~2 years ago.

**Comment by sosedoff** [comment]
Cool, i'll update the dep

**Comment by natiki** [comment]
Cool. Will test new version when you release it and then hopefully I can close this out.

**Comment by sosedoff** [comment]
@natiki 0.10.0 is released with updated dependencies.
