### ISSUE TITLE
Greenplum support

### ISSUE THREAD

**Issue by leotu** [sosedoff/pgweb#374]
https://greenplum.org/

Please support Greenplum Database 4.3.x and 5.X

**Comment by cbandy** [comment]
What error(s) do you get when using Greenplum?

**Comment by sosedoff** [comment]
@leotu could you be more specific with your request?

**Comment by sosedoff** [comment]
Closing until there's some background for this issue. Personally, i don't have time to research into Greenplum integration, so cant really add any useful info.
