### ISSUE TITLE
Windows version won't even connect when insecure....

### ISSUE THREAD

**Issue by natiki** [sosedoff/pgweb#376]
Hi,

Started a basic cluster on windows with:

```
cockroach start --insecure --http-port=8101
cockroach start --insecure --store=node2 --host=localhost --port=26258 --http-port=8102 --join=localhost:26257
cockroach start --insecure --store=node3 --host=localhost --port=26259 --http-port=8103 --join=localhost:26257
```
I can connect with DBeaver, Visual Studio Enterprise but pgWeb throws an error of:

> Cannot access virtual schema in anonymous database

Screenshot has the details:

![image](https://user-images.githubusercontent.com/4738140/45359907-574a8180-b611-11e8-91f4-f1a3d19c9c45.png)

**Comment by sosedoff** [comment]
Yeah i think i've seen this error, you need to connect to a valid user schema, not the virtual one like in your screenshot. I have ran only basic tests with cockroach, so its not officially supported by pgweb at this time, although they're compatible

**Comment by sosedoff** [comment]
Closing this for now: feel free to reopen if you'd like to improve integration with cockroachdb
