### ISSUE TITLE
json: unsupported value: NaN

### ISSUE THREAD

**Issue by ayang** [sosedoff/pgweb#385]
2018/10/26 21:56:40 [Recovery] panic recovered:
GET /api/tables/public.some_table/rows?limit=100&offset=0&_=1540562079027 HTTP/1.1
Host: localhost:8081
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: keep-alive
Referer: http://localhost:8081/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
X-Requested-With: XMLHttpRequest
X-Session-Id: 901e4e84-05a3-9fda-d945-3210f8c653fb

json: unsupported value: NaN
/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 (0x4298d8)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/render/json.go:26 (0x75ecff)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:477 (0x764e22)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:501 (0x764ffb)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:501 (0x764ffb)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/api/middleware.go:77 (0x823cd7)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/api/api.go:364 (0x821339)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x763392)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/api/middleware.go:31 (0x824fbe)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x763392)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/recovery.go:45 (0x7719b9)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x763392)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/logger.go:77 (0x770dd6)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x763392)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/gin.go:290 (0x768fec)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/gin.go:271 (0x768a02)
/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 (0x67110b)
/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1830 (0x66d330)
/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 (0x456a60)

**Comment by sosedoff** [comment]
I'll have a look.

**Comment by sosedoff** [comment]
Which pgweb version are you using?

**Comment by ayang** [comment]
Pgweb v0.9.12 (git: 9af721176bf7b41366f0de8251fff0b47da8fce3)

**Comment by sosedoff** [comment]
Should be fixed with latest 0.10.0 release
