### ISSUE TITLE
Latest version as of 12/5/2018 triggers antivirus

### ISSUE THREAD

**Issue by JNFoo** [sosedoff/pgweb#392]
Hi, the latest windows version executable (as of 12/05/2018) gets quarantined by AVG as Win32:Xpaj-gen. This variant has known aliases: 
Virus:Win32/Xpaj.gen!C (Microsoft)
W32/Xpaj.b (McAfee)
W32.Xpaj.B (Symantec)
Virus.Win32.Xpaj.gen (Kaspersky)
Virus.Win32.Xpaj.A (v) (Sunbelt)
Win32/Xpaj (AVG)

From MS Security encyclopedia:
Summary
Virus:Win32/Xpaj is a family of viruses that spread by infecting local files and removable and network drives. The virus attempts to download arbitrary files which may be detected as other trojans.
The virus is capable of infecting executable (EXE), driver (DLL), screen saver (SCR) and system (SYS) files.
In the wild, we have observed this virus distributed via file sharing sites, masquerading as a key generator. It may also arrive on your computer via a drive-by download.

-JNFoo

**Comment by sosedoff** [comment]
This is quite interesting. Nothing has changed in regards to the build/distribution process in years.
I don't have a windows machine around, but i'll ask someone to look into this.

**Comment by sosedoff** [comment]
I have ran the binary through Windows Defender Security Intelligence reporting tool as well as VirusTotal database, both reports came back clean. The trigger could be related to the fact that pgweb has embedded content (html/css/js). Closing due to false positive.

**Comment by sosedoff** [comment]
Attaching the review from Microsoft.

<img width="928" alt="screenshot 2019-01-25 15 52 00" src="https://user-images.githubusercontent.com/71051/51774809-344cd580-20b9-11e9-9038-029995aa26ac.png">

**Comment by JNFoo** [comment]
Good to hear! Thank you for closing the loop on this. 
Best,
-JNFoo
