### ISSUE TITLE
0.11.0 release missing windows amd64

### ISSUE THREAD

**Issue by mattburton** [sosedoff/pgweb#402]
Just a heads up that the Windows amd64 version is missing in the 0.11.0 release. I was able to get up and running on 386 without issue as a temporary workaround. Thanks for all the hard work on such an amazing tool! I have to switch back and forth between Macs and Windows for work and the state of Postgres client apps on Windows is _abysmal_ - I was so happy to find pgweb.

**Comment by sosedoff** [comment]
Thanks! I re-uploaded the win/amd64 release

**Comment by mattburton** [comment]
Excellent thanks!
