### ISSUE TITLE
[Feature Request] Show view definition in Structure tab

### ISSUE THREAD

**Issue by mattburton** [sosedoff/pgweb#403]
The ability to see a pretty printed, syntax highlighted display of the definition of a given view / materialized view in the Structure tab would be extremely handy. The command `select pg_get_viewdef('{{view_name}}', true);` is easy enough to remember, but I wind up needing to copy and paste the output into a text editor to see everything, especially for views with large definitions.

**Comment by sosedoff** [comment]
This is implemented in #594

**Comment by mattburton** [comment]
Hey - thanks! I'll take a look at this for sure - actually have a need for an embedded db UI sort of deal and was considering pgAdmin but pgweb is far simpler to setup - might be a better match - perfect timing! (and happy to see work has continued on this project - great stuff!)

**Comment by sosedoff** [comment]
0.12.0 binary release will be available pretty soon, some time this week. If you need to test the changes you can build the project from source (via `make build`).
