### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by majestique** [sosedoff/pgweb#411]
After installing it on CentOS:

> curl -s https://api.github.com/repos/sosedoff/pgweb/releases/latest \
>   | grep linux_amd64.zip \
>   | grep download \
>   | cut -d '"' -f 4 \
>   | wget -qi - \
>   && unzip pgweb_linux_amd64.zip \
>   && rm pgweb_linux_amd64.zip \
>   && mv pgweb_linux_amd64 /usr/local/bin/pgweb

We just execute: `pgweb --host localhost --user myuser --pass mypw --db mydb`

and it should run on port 8081?

I keep on getting this:
![image](https://user-images.githubusercontent.com/19336285/52380602-4c124b00-2a23-11e9-814e-6772168acd1b.png)

**Comment by sosedoff** [comment]
Well, if the authentication credentials are correct - yes, you should be able to start pgweb and access it on port 8081. Looks like you might have some modifications made to authentication methods in your `pg_hba.conf` file, which produces the error you're seeing.

**Comment by majestique** [comment]
I got it to run and it looks like it's listening but I can't seem to connect.
![image](https://user-images.githubusercontent.com/19336285/52394168-4dad3480-2a5e-11e9-95fb-f1ae130de40e.png)

![image](https://user-images.githubusercontent.com/19336285/52394196-64538b80-2a5e-11e9-8aec-bdd42c8b2daa.png)


my firewall is open on port 8081 as well:
![image](https://user-images.githubusercontent.com/19336285/52394330-cd3b0380-2a5e-11e9-9b3b-90efe4e61381.png)

Any idea why it's not working?

**Comment by majestique** [comment]
Got it to run with `--bind=0.0.0.0`
