### ISSUE TITLE
Failed to fetch data when the table is in camelCase format

### ISSUE THREAD

**Issue by gustavohenrique** [sosedoff/pgweb#413]
I have a table named `classSchedule` and I got an error when I click in the name in sidebar:

```
ERROR: pq: relation "public.classschedule" does not exist
```

![error](https://user-images.githubusercontent.com/51675/52498372-caa3ef80-2bbf-11e9-9027-f1f11be3d0c5.png)

Maybe it is related to #356

**Comment by sosedoff** [comment]
Should be fixed in 0.11.2 release
