### ISSUE TITLE
How do things like cleanupIdleSessions interplay with database/sql's connection pooling

### ISSUE THREAD

**Issue by budden** [sosedoff/pgweb#425]
This question arised from learning this one: 

http://go-database-sql.org/connection-pool.html

I did neither careful code study nor experiments, but there is a feeling that there's no need for files like pkg/api/session_cleanup.go. Instead it should be sufficient to configure an sql's connection pool feature. Am I wrong?

**Comment by sosedoff** [comment]
The automatic session cleanup was added for managing pgweb internal sessions, so it has nothing to do with db pooling. Connections could be closed automatically on the db side, but that does not mean that they're inactive on the pgweb's side.
Pgweb sessions are tied to the browser session, so if you loose the tab you wont be able to get your session back, hence the need for cleanup. Primarily designed for environments where pgweb is being shared by customers.
