### ISSUE TITLE
Setting port in command line option has no effect in browser

### ISSUE THREAD

**Issue by giminni** [sosedoff/pgweb#426]
If I set the port command line option to a different address than 5432 does not reflect in browser

My command line looks like 
```
pgweb --sessions --skip-open --port=12345 --listen=9080 ...
```

Open the browser \<host\>:9080 the port field always shows 5432

**Comment by sosedoff** [comment]
When you specify `--port` CLI params its only meat to be used to configure the server connection, it does not have anything to do with what's displayed in the web UI. 5432 port in the UI is the default.

**Comment by JoeRoddy** [comment]
For others searching for this, the `listen` option is what sets the web client's port.

`pgweb --url <connectionString> --listen=6969`
