### ISSUE TITLE
Functionality to terminate query from the UI

### ISSUE THREAD

**Issue by foadgr** [sosedoff/pgweb#428]
It would be useful to incorporate some functionality to terminate a query after a given time interval. In other words, a superuser (i.e. `postgres`) that is not connected to the database would run:
```sql 
SELECT
  pid,
  now() - pg_stat_activity.query_start AS duration,
  query,
  state
FROM pg_stat_activity
WHERE (now() - pg_stat_activity.query_start) > interval '[some_number_of] minutes';

SELECT pg_cancel_backend(__pid__);
```
Additional functionality could be added to toggle `some_number_of` minutes.

**Comment by sosedoff** [comment]
@foadgr There's a way to terminate the query from UI: go to activity page and locate the query you're about to shut down, then scroll all the way to the right where you can find the button "stop". That should do it. 

I know, the UX sucks, but unfortunately i don't have any spare time to make it better at this time. Reworking the table view into something more readable has definitely been on my radar for quite some time.

**Comment by foadgr** [comment]
@sosedoff Thanks for the reply. The 'stop' button works for some processes (backend/ongoing), the query pane does still freeze up while running larger queries. But stopping the query directly from `psql` works just as well. I'm okay closing out this issue or moving to enhancements.
