### ISSUE TITLE
Pgweb hangs on rows with bytea columns

### ISSUE THREAD

**Issue by sarneeh** [sosedoff/pgweb#429]
I have a table with one `bytea` column where I'm storing small images. Unfortunately, if I'm having like more than 10 rows there, `pgweb` totally hangs when I want to see the rows and it's unresponsive.

**Comment by sosedoff** [comment]
Yeah, this is the sad default behavior. I guess we could just show some kind of placeholder with the column size instead of loading binary data if the size exceeds the threshold.

**Comment by sarneeh** [comment]
@sosedoff Sounds reasonable. I'm out of time right now but in a month I should have more free time so I could take a try on this. Of course, if someone would like to take this faster then just do it :smiley:

**Comment by sosedoff** [comment]
Im closing this stale issue.

**Comment by ruzrobert** [comment]
so sad this was never done. one of the simpliest features done in phpmyadmin. makes pgweb completely unusable for our case.

**Comment by sosedoff** [comment]
@ruzrobert I understand that some features are missing in Pgweb, but you have to understand that project development is done 100% using spare time. If you'd like to see this implemented, feel free to contribute some code.
