### ISSUE TITLE
Unable to run behind nginx

### ISSUE THREAD

**Issue by aporwal17** [sosedoff/pgweb#430]
After done with the installation. i ran pgweb with below command.

`./pgweb_linux_amd64 --url "postgres://<username>:<password>@<host>/<db>" --ssl=require --readonly --bind <ip> --prefix=db --debug &
`
and I tried to run web behind my Nginx but when hit the server, i am getting issue as:

**"Content-Type header [application/x-www-form-urlencoded; charset=UTF-8] is not supported"**

Is this the issue with Nginx config or pgweb ?

Nginx config is :

```
location /db {
            default_type "application/x-www-form-urlencoded; charset=utf-8";
            proxy_pass http://<ip>:8081/db;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_connect_timeout 1;
            proxy_send_timeout 30;
            proxy_read_timeout 30;
            proxy_set_header    Authorization "";
            proxy_hide_header   Authorization;
}
```
Any help on this ?

**Comment by aporwal17** [comment]
@sosedoff : Can you please help here ? Am i missing anything?

**Comment by sosedoff** [comment]
What what i can see here you have `default_type` set with invalid content type, like your error message states. To see if nginx is really a culprit here, run the following commands:

```
curl -i http://IP:8081/db
curl -i http://IP/db 
```

These commands will print out all response headers. First returns them directly off of pgweb, second one is from nginx. If your header does come from nginx - that's your problem (most likely).

**Comment by aporwal17** [comment]
@sosedoff Thanks for your quick response. I have removed the "default_type" from the Nginx code, still getting same error.
Also when i hit directly from command line as you mentioned. `curl -i http://IP:8081/db` : i am getting as 

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Wed, 29 May 2019 10:58:05 GMT
Transfer-Encoding: chunked
```
All other things are working with Nginx. Not sure what i am missing in config.
```
location /db {
            proxy_pass http://172.1.102.228:8081/db;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_connect_timeout 1;
            proxy_send_timeout 30;
            proxy_read_timeout 30;
            proxy_set_header    Authorization "";
            proxy_hide_header   Authorization;
}
```

Any idea ?

**Comment by aporwal17** [comment]
i got the issue there was an issue in Nginx config. There was a path which redirect /api to other place and pgweb is also using the same path to redirect. i will fix this issue.

Thanks for your help.
