### ISSUE TITLE
Add support for PostgreSQL scram-sha-256 authentication

### ISSUE THREAD

**Issue by XhstormR** [sosedoff/pgweb#431]
I used the following command to initialize the database, the password is 123456:
```
initdb.exe -A scram-sha-256 -E UTF8 --no-locale --lc-messages="Chinese (Simplified)_China.936" -U 123 -W -D D:\12345
```

Then I use the following command to connect to the database, but the connection failed:
```
pgweb_windows_amd64.exe   /debug  /user:123 /pass:123456 /db:postgres
Pgweb v0.11.2 (git: d3aaf8f5dbe5032734aeaea9c44eb79ef61eeaec)
Creating a new client for: postgres://123:123456@localhost:5432/postgres?sslmode=disable
Failed query: SELECT version()
Args: []
Server connection string: postgres://123:123456@localhost:5432/postgres?sslmode=disable
Connecting to server...
Error: pq: unknown authentication response: 10
```

I think the problem may be caused by scram-sha-256, just like https://github.com/grafana/grafana/issues/14662.

**Comment by sosedoff** [comment]
Interesting, they mention the change has landed in lib/pq, so i guess bumping up the dependency should fix this.

**Comment by XhstormR** [comment]
Yes, I think so too.
