### ISSUE TITLE
would it be able to update data by simply clicking?

### ISSUE THREAD

**Issue by xuze1993** [sosedoff/pgweb#432]
just like some "for update" on PLSQL

**Comment by sosedoff** [comment]
I dont understand your question, @xuze1993

**Comment by xuze1993** [comment]
Modify and commit data from displaying SELECT TABLE results instead of using UPDATE TABLE stuff for quick changes. @sosedoff

**Comment by sosedoff** [comment]
Oh you mean editing stuff from the results view? Yeah, this seems like the most requested feature but i don't have much time these days. Im going to close since there are a few similar tickets already.
