### ISSUE TITLE
need to remove search_path from postgres url before running pg_dump

### ISSUE THREAD

**Issue by rexroof** [sosedoff/pgweb#433]
I added a search_path to my postgres url to support a different default schema in pgweb.

this causes an issue with the SQL export feature using pg_dump:

```
{"error":"error: exit status 1. output: pg_dump: [archiver (db)] connection to database \"\" failed: invalid URI query parameter: \"search_path\"\n","status":400}
```

thats the json response when I try and archive anything while search_path is in my database url setting.

**Comment by sosedoff** [comment]
Could you paste the full url here (excluding sensitive data obv)?

**Comment by rexroof** [comment]
```    
postgres://newt:XXXXX@localpg:5432/yms?sslmode=disable&search_path=yms
```

I'm running in kubernetes, "localpg" is my postgresql service name.

**Comment by sosedoff** [comment]
Got it, thanks for the additional info. I will fix this in the next version which im planning to release this week.
