### ISSUE TITLE
Query does not work behind web application firewall

### ISSUE THREAD

**Issue by mkacmaz** [sosedoff/pgweb#458]
I am facing with this issue when I try to run a query on Mindsphere platform. For example this query works:
"SELECT *  FROM blabla" , but if I use "where" clause in my query,  it doesn't work. If I understand correctly, there is a web application firewall behind and it blocks my query to prevent sql injection attacks. I get 461 http status from backend.

So, maybe we encode this query before sending to backend and decode once received it. 

![image](https://user-images.githubusercontent.com/3417234/76954903-38256200-6922-11ea-936e-74768372c872.png)

**Comment by mkacmaz** [comment]
I viewed the source and it already tries to decode base64 string but on UI side query is not sent as base64 encoded

**Comment by sosedoff** [comment]
I don't think this has anything to do with pgweb. If you're getting HTTP 461 then your provider or something in between is doing the filtering. Pgweb itself will never return such a code.
