### ISSUE TITLE
Waiting for the port being available when runing inside a docker container

### ISSUE THREAD

**Issue by zb3** [sosedoff/pgweb#462]
When running pgweb with postgres via `docker-compose`, pgweb can in some cases start before the database port is available which causes the container to exit with `connection refused`.
  
There are issues #158 and #216, but even though it now "happens" to work, the race condition is still there, because there's no mechanism here to actually wait for the port to be available, The `depends_on` option unfortunately doesn't do that either (see https://docs.docker.com/compose/compose-file/#depends_on).

In my case, pgweb always starts before the port is ready when postgres is run for the first time, with uninitialized data directory (I also have an init script to create the schema).
  
One possible solution I see is to create an entrypoint script which'd use [wait-for-it.sh](https://github.com/vishnubob/wait-for-it). This way, the timeout can be configured from within `docker-compose.yml` directly via the `WAITFORIT_TIMEOUT` variable. However that script doesn't parse URIs...

**Comment by zb3** [comment]
For anyone with the same problem, as a workaround I currently use a separate image and [wait-for-it.sh](https://github.com/vishnubob/wait-for-it). Here's my Dockerfile:
```
FROM sosedoff/pgweb

RUN apk add --no-cache bash

COPY wait-for-it.sh entrypoint.sh ./

ENTRYPOINT ["./entrypoint.sh"]
CMD ["/usr/bin/pgweb", "--bind=0.0.0.0", "--listen=8081"]
```

And `entrypoint.sh`:
```
#!/bin/sh

if [ -n "$DATABASE_URL" ]; then
  db_host="${DATABASE_URL%/*}"
  db_host="${db_host##*[/@]}"
else
  db_host="127.0.0.1:5432"
fi

./wait-for-it.sh "$db_host"

"$@"
```

**Comment by sosedoff** [comment]
Im fairly sure this is no longer a problem. We have a service health check on dependent container in here https://github.com/sosedoff/pgweb/blob/master/docker-compose.yml#L33
