### ISSUE TITLE
pre-build pgweb on Debian 9 can't find css and js files over nginx proxy

### ISSUE THREAD

**Issue by ashouh** [sosedoff/pgweb#464]
The nginx proxy (https) for pgweb running on 8081 port works, but can't find css and js files that index page needs. so the site not workable. Try to set a root in the nginx configure and put static folder (from src) under the root, missing css, js files solved, but the index page is blank. Can you help me for this issue? Thanks.

**Comment by sosedoff** [comment]
Can you provide any configuration and pgweb startup flag? Also, which pgweb version are you running?

**Comment by ashouh** [comment]
Pgweb v0.9.7 (git: 4833a76b05338e8001eabfda632d49850cc68d25)

installed at /usr/local/bin/pgweb

/usr/local/bin/pgweb --bind=0.0.0.0 --listen=8081

nginx configure:

server {
    listen [::]:8083 ssl;
    listen 8083 ssl;

    server_name www.mysite.com;

    ssl_certificate /etc/ssl/certs/bundle.crt;
    ssl_certificate_key /etc/ssl/private/site.key;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location = / {
        proxy_pass http://127.0.0.1:8081;    
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

**Comment by sosedoff** [comment]
Try the latest version, 0.9.7 is way too old (from apr 2017)

**Comment by ashouh** [comment]
Tried the latest version 0.11.6 with the nginx, the same result as version 0.9.7. Switched to Apache2 2.4 with configure (proxy part) with ssl:

ProxyPreserveHost On
ProxyPass / http://127.0.0.1:8081/
ProxyPassReverse / http://127.0.0.1:8081/

It works!

**Comment by sosedoff** [comment]
I think your issue is strictly nginx-related. If you're able to see the pgweb login screen but not the assets you should check your nginx/pgweb log to see which requests are getting proxied.
