### ISSUE TITLE
[Feature Request] Option to defer initClient() when connection URL is specified

### ISSUE THREAD

**Issue by joekohlsdorf** [sosedoff/pgweb#471]
If pgweb is started passing it a connection URL it immediately tries to open the connection to the server on startup and dies with exit code 1 if the server is not reachable.

This makes it unsuitable for running it in Docker Compose alongside a Postgres container, unless I specify the connection details manually.

I propose a new option to defer this function call to when the user actually starts interacting with the Web UI. If the server is not (yet) reachable it would be helpful to show an error in the UI instead of exiting.

**Comment by Okeanos** [comment]
Just noticed that #462 basically describes the same feature. I'd also be very much interested in this.

**Comment by sosedoff** [comment]
Use service health checks in docker compose, example: https://github.com/sosedoff/pgweb/blob/master/docker-compose.yml#L33
