### ISSUE TITLE
[Feature Request] Ability to enlarge query area.

### ISSUE THREAD

**Issue by charlieSplittstoser** [sosedoff/pgweb#472]
The query area feels very small. I would sometimes like to expand it to be about half the vertical height of the screen when I am working on a query.

Conceptual image: https://prnt.sc/stbvcl

**Comment by foadgr** [comment]
Agreed -- @sosedoff an adjustable/draggable query pane would be very helpful to view an entire query.

**Comment by sosedoff** [comment]
This is a duplicate of #118, which is sadly i dont have time to work on :(
