### ISSUE TITLE
[Feature Request] Ability to use AWS RDS IAM authentication for connecting to database

### ISSUE THREAD

**Issue by foadgr** [sosedoff/pgweb#476]
A very helpful feature would be the ability to connect to a database via AWS RDS IAM authentication. Currently the only workaround is custom shell scripting to implement `generate_db_auth_token` with IAM credentials then pipe that into a connection url as a pgweb argument.

**Comment by sosedoff** [comment]
Whats wrong with the approach you've described? I've been using shell+awscli scripting to access RDS databases and it seems to work fine. There was a batch of new features related to resource discovery in #391, but i've paused all the work on that branch for quite some time (got work to do). 

The scope of IAM auth is also a bit outside of pgweb's concern, in addition to edge cases like expiring auth tokens. You're free to fork the project and add the missing functionality if you'd like, i double i will implement anything like that in near future.

**Comment by foadgr** [comment]
Thanks for referring to the pull request, I'll go from there with any new work on this functionality.
