### ISSUE TITLE
Error: pq: schema "dbms_alert" does not exist

### ISSUE THREAD

**Issue by gabrieljones** [sosedoff/pgweb#480]
```
> docker run -p 8082:8081 -e DATABASE_URL='postgres://xxxxx:xxxxxx@xxxxx.xxxxx.com:5444/xxxxx?sslmode=disable' sosedoff/pgweb
Pgweb v0.11.6 (git: 3e4e9c30c947ce1384c49e4257c9a3cc9dc97876) (go: go1.13.7)
Connecting to server...
Connected to  
Checking database objects...
Error: pq: schema "dbms_alert" does not exist
```

When I launch without DATABASE_URL and then login to the same db
`http://localhost:8081/api/objects` responds with:
```
{"error":"pq: schema \"dbms_alert\" does not exist","status":400}
```

My other database tool is Intellij IDEA.
I don't see `dbms_alert` in any part of the db object browser in IDEA.

**Comment by sosedoff** [comment]
No idea why, maybe some permissions error? You can see the queries used in API endpoints here: https://github.com/sosedoff/pgweb/blob/master/pkg/statements/sql.go#L130 

Can you run the query and report back what you find?

**Comment by gabrieljones** [comment]
`[2020-08-03 21:04:39] [3F000] ERROR: schema "dbms_alert" does not exist`

**Comment by gabrieljones** [comment]
`select * from pg_catalog.pg_namespace where nspname = 'dbms_alert';`
returns one row

**Comment by gabrieljones** [comment]
`select count(*) from pg_catalog.pg_namespace;` returns 38
but IDEA only shows me one. I am assuming its the one schema the user actually has permissions to see.

**Comment by gabrieljones** [comment]
`select has_schema_privilege('dbms_alert', 'USAGE');`
throws error
`[3F000] ERROR: schema "dbms_alert" does not exist`

**Comment by sosedoff** [comment]
looks like something is up with your permissions and i've not seen it before. what pg service are you using?

**Comment by gabrieljones** [comment]
https://github.com/sosedoff/pgweb/issues/222 is related

IDEA is able to ignore this in its db object browser

This is an enterprise postgres service managed by a whole other team.

How do I find out what pg service I am using?

**Comment by sosedoff** [comment]
i don't know. you can check the pg version in IDEA somehow but i doubt it would have anything useful in the version string.
or you can guess from the host dns name.

**Comment by gabrieljones** [comment]
`SELECT version();`
returns
```
EnterpriseDB 9.6.17.24 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23), 64-bit
```

**Comment by gabrieljones** [comment]
My recommendation is to try to come up with a way to gracefully interpret a `3F000` error on `has_schema_privilege` as `false`.
Or maybe something along these lines: https://github.com/metabase/metabase/issues/10139

**Comment by gabrieljones** [comment]
I see now that this is likely an issue exclusive to EnterpriseDB and not to Postgres itself. Apparently our "Postgres" service is more than/less than just plain old Postgres.
sigh

**Comment by gabrieljones** [comment]
Would be nice if pgweb could work around this so that EnterpriseDB would be handled despite such a small surface wrinkle, but I guess thats up to you guys or anyone who cared to fork pgweb for that purpose.

**Comment by sosedoff** [comment]
i mean if you have a workaround - feel free to send PR and i can incorporate the changes if they're not interfering with regular postgres stuff. otherwise i dont have a lot of free to experiment with this integration (not i have access to enterprisedb)

**Comment by sosedoff** [comment]
No capacity to work/explore this angle, unfortunately. Feel free to reopen in this is still relevant to you.
