### ISSUE TITLE
Error: pq: Unsupported startup parameter: extra_float_digits

### ISSUE THREAD

**Issue by mustpax** [sosedoff/pgweb#481]
Hi,

I'm trying to connect to a postgres db that's behind PGBounce. It appears that the `extra_float_digits` is incompatible PGBounce https://github.com/Athou/commafeed/issues/559 . Unfortunately, I don't have control over the configs for instance PGBounce so I cannot use the `ignore_startup_parameters` fix.

Is it possible for me to use `pgweb` to connect to this database?

Error message:

```
$ pgweb --readonly --url "postgresql://[redacted]?sslmode=disable"
Pgweb v0.11.6 (git: 3e4e9c30c947ce1384c49e4257c9a3cc9dc97876) (go: go1.13.7)
Connecting to server...
Error: pq: Unsupported startup parameter: extra_float_digits
```
See also: https://github.com/lib/pq/issues/475

**Comment by sosedoff** [comment]
Looks like we'll have to wait till this gets fixed in `lib/pg`.
