### ISSUE TITLE
InsecureSkipVerify for self signed certificates

### ISSUE THREAD

**Issue by weetie** [sosedoff/pgweb#485]
In order to use self signed certificates it would be great to set this with a command line argument, for example --ssl-skipverify

**Comment by sosedoff** [comment]
i dont remember all the options, but you can add `?sslmode=disable` to your connection string to skip any verification.
is that what you're looking for ?

**Comment by weetie** [comment]
No, I need the SNI-header of the connection, but I also want to use a self-signed one, lib/pq can do this perfectly, pgweb just needs to pass this parameter

**Comment by sosedoff** [comment]
ok, i'll take a look. if you have a PR - send it over as well, would be helpful.

**Comment by sosedoff** [comment]
If you're referring to `InsecureSkipVerify: true` option in tlsConfig, then it should be already included in libpq.
