### ISSUE TITLE
access token for embedded pg web

### ISSUE THREAD

**Issue by arunjsoegp** [sosedoff/pgweb#486]
I was trying to integrate pg web in our application as an embedded. I could see few issues in-terms of authentication and I would like to know is there any other way I can get token by using api and load pg web as embedded.

What I really want is ?
* Integrate pg-web as an embedded in our web application.
* Api specification for authentication 

Do you have api specifications / documentation ?

If possible kindly provide me some documentation for integration.

**Comment by sosedoff** [comment]
There's no official API, docs for usage:

- https://github.com/sosedoff/pgweb/wiki/Usage
- https://github.com/sosedoff/pgweb/wiki/Connect-Backend
