### ISSUE TITLE
-bash: pgweb: command not found

### ISSUE THREAD

**Issue by tayyabvohra** [sosedoff/pgweb#488]
I am using linux CentOS VPS server , I have manually downloaded pgweb_linux_amd6.zip and move on the following /usr/local/bin/pgweb

still I am getting 

-bash: pgweb: command not found

while if I run manually from pgweb folder i also got 

-bash: pgweb: command not found

I have followed these linux steps but not worked

https://github.com/sosedoff/pgweb/wiki/Installation

Any help will be appreciated alot

**Comment by sosedoff** [comment]
does not appear to be an issue with archives - you probably not extracting the archive in a right place or not extracting it at all. try to download the release archive manually and run `unzip` on the file (dont move stuff around just yet). you should be able to see and execute the binary. after that is working you can move pgweb to any directly that's part of `PATH` env var so you can run `pgweb` without specifying the full path.
