### ISSUE TITLE
Mysql support

### ISSUE THREAD

**Issue by santagada** [sosedoff/pgweb#49]
How against adding mysql support would you be? I find your tool very direct and to the point and mysql has nothing remotely like it (they don't even have an open source gui tool like pgadmin) so I think it would be pretty cool. I know that this would add a layer of compatibility and probably would make working with css/html morecomplex as you have to support both but it is so much better than working with phpmyadmin that I think you might gain a lot of users/contributors.

If you are interested I or someone looking at this can start a fork to add support in the hopes that it gets merged back.

ps: yes mysql is a worse database manager, please tell that to wordpress core :)

**Comment by smurfpandey** [comment]
@santagada I know this is a old thread, but I wanted to share my fork in case you still need a similar tool for MySQL.  https://github.com/smurfpandey/mysqlweb
