### ISSUE TITLE
Arm64  builds

### ISSUE THREAD

**Issue by camccar** [sosedoff/pgweb#496]
I wanted to give this a try on my raspberry pi server running arm64 but the build and dockerfile fails. It's not listed as a target in the makefile

**Comment by sosedoff** [comment]
There is a ARMv5 build but i'm not sure if its the right one. What kind of RPI do you have?

**Comment by camccar** [comment]
> There is a ARMv5 build but i'm not sure if its the right one. What kind of RPI do you have?

I finally got it to work by converting it to a go modules project with `go mod init` and running a `go mod tidy`. Finally just a `go build` in go 1.15. Might have been a few other commands in there but the go compiler listed them. Works fine like this. Not sure why you aren't using go modules yet.  

https://github.com/camccar/pgweb

**Comment by sosedoff** [comment]
RE modules: This is an old project so i just haven't gotten a chance to upgrade to modules. 

RE build: I don't see you having binary build instructions added here https://github.com/camccar/pgweb/blob/master/Makefile#L57-L59, if you have them feel free to submit a PR and i will incorporate those builds into target releases.

**Comment by camccar** [comment]
I’ll try to get to making a PR this weekend. If all the test still pass

**Comment by camccar** [comment]
I just didn't understand how to use dep. I can build it now without modules. but it is missing the arm64 target. I added that in the PR. Would be awesome if you got an arm64 version in docker hub. In the mean time I just wrote another dockerfile to reference it locally.
