### ISSUE TITLE
colum header freeze in the "Rows" tab

### ISSUE THREAD

**Issue by rachamaduguravi** [sosedoff/pgweb#502]
Hi,

In the "Rows" tab on the top, in which the table/view row's contents are displayed, might there be a way to freeze the "column headings" such that when we scroll down the "column headings" continue to be visible?

right now, when rows are many, when we scroll down the page, the "column headings" scroll out of view

thanks!

**Comment by sosedoff** [comment]
Nope, not in the public pgweb version.
