### ISSUE TITLE
Request: Push docker images to Gihub Container Registry

### ISSUE THREAD

**Issue by joao-p-marques** [sosedoff/pgweb#503]
Hi :wave: 

Would it be possible to push the Docker image also to the [Gihub Container Registry](https://docs.github.com/en/packages/guides/about-github-container-registry) (ghcr.io)?

It would help avoid the new pull limits and some possible network restrictions from DockerHub.

It can be easily done with a Github Action. Is this on the roadmap?

@Tecnativa TT27819
cc @Yajo

**Comment by sosedoff** [comment]
It is now :)

**Comment by sosedoff** [comment]
Should be available in the next release
