### ISSUE TITLE
Update to go modules

### ISSUE THREAD

**Issue by roopakv** [sosedoff/pgweb#504]
This tool is installable via brew. In order to maintain it easier when go 1.17 rolls around could the maintainers please add go modules support.

https://github.com/Homebrew/homebrew-core/issues/47627

**Comment by lelvisl** [comment]
@roopakv look at this - https://github.com/sosedoff/pgweb/pull/508

**Comment by roopakv** [comment]
That looks promising! Thank you for making the PR :)

**Comment by lelvisl** [comment]
#509

**Comment by roopakv** [comment]
@lelvisl awesome! please make a new release with the go modules stuff so that we can update the brew side of the world
