### ISSUE TITLE
show full contents of a cell

### ISSUE THREAD

**Issue by yuis-ice** [sosedoff/pgweb#505]
I have exactly the same issue to [Cannot expand width of column contents · Issue #51 · sosedoff/pgweb](https://github.com/sosedoff/pgweb/issues/51), basically I cannot see full content of an cell. In the issue seems the issue was solved and now I should be able to expand cells by double clicking, but it doesn't work. 

I mean query tab, example result like this: 

![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_6dc8206d-a610-431f-8619-4d32004915b0.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_6dc8206d-a610-431f-8619-4d32004915b0.png)

version: latest

**Comment by sosedoff** [comment]
double clicking on the text has been removed due to confusion: lots of people thought they could edit fields.
you can right-click on the cell and copy the value via the context menu.

**Comment by helloyi** [comment]
It is very inconvenient to display on other platforms after copying.  
You can add a scroll bar, right? Or some other way.

Please!
