### ISSUE TITLE
Client certificate support

### ISSUE THREAD

**Issue by wepecko** [sosedoff/pgweb#514]
Hello, there is already one closed ticket about this topic to use a certificate in login process.
is there any chance your tool would support this?
we use standard way with user/pass to dbmachine/port and a certificate as an extra layer of security.
cheers
PB.

**Comment by sosedoff** [comment]
I could fix this if you can provide your dev setup / environment. I dont use pgweb with certs right now, so dont really have a good way of reproducing the issue.

**Comment by sosedoff** [comment]
Closing due to previous comment being unaddressed.
