### ISSUE TITLE
Installation issue on dokku (similar to heroku): cannot find module providing package embed

### ISSUE THREAD

**Issue by JanRuettinger** [sosedoff/pgweb#515]
I use dokku to deploy pgweb to my web server. Dokku works like Heroku but let's you deploy software on your own server.
I have cloned the repo and pushed it to the dokku server to start the deployment. 

This issue occurred:
```
-----> Running: go install -v -tags heroku github.com/sosedoff/pgweb
       build github.com/sosedoff/pgweb: cannot load embed: cannot find module providing package embed
```

Any ideas on how to fix it?

**Comment by JanRuettinger** [comment]
Version 1.12.17

**Comment by sosedoff** [comment]
Thanks, i'll get this fixed.
