### ISSUE TITLE
CSS not friendly for long columns

### ISSUE THREAD

**Issue by rmannibucau** [sosedoff/pgweb#517]
Hi,

It would be great to have some way to see long record column entries (whatever solution it is, overflow: auto with ellipsis:unset in the css or a popup or a drawer etc...).
Currently it requires to either download the records (which is not desired most of the time and requires to use an editor to see the full record).

If it helps the column I'm having a hard time with contains raw JSON data (in a varchar column but i guess it would be the same with JSON or JSONB columns).

Side note: not using go embedded static resources but a directory where static resources are would at least enable to patch/override the CSS without using a proxy so maybe another option can be to let CSS be injected somehow.

Romain

**Comment by sosedoff** [comment]
CSS injection (or any other resource for that matter) is def a no-go. If you have a CSS styling fix or anything of that nature - please open a PR, we can work something out. Im gonna close this for now due to inactivity.

**Comment by rmannibucau** [comment]
@sosedoff well it is not really css injection since it would be a docbase folder (as in most web server) instead of making an all in one binary.
That said, as you probably noticed, this issue is not about injecting CSS - was just a nice way to customize the css if needed (which is *not* css injection btw ;)) - but about ensuring long columns can be read in the UI since it is not the case as of today so I guess you closed it a bit too fast.
You can try with any JSON and see that the column is unreadable.
I don't know if just css is ok or if you prefer a "view in modal" behavior but currently the UI is not usable for such tables without playing with the browser dev panel.
