### ISSUE TITLE
Explain Query button is potentially misleading

### ISSUE THREAD

**Issue by tim-ings-vgw** [sosedoff/pgweb#518]
Hey, just wanted to bring up that the "Explain Query" button is potentially misleading and could cause accidental loss of data as it actually runs `EXPLAIN ANALYZE` not just `EXPLAIN` as the button label initially suggests. 

Relevant code here: https://github.com/sosedoff/pgweb/blob/9d1a3fd533900099c9a70fb7bfc84590073a9b1e/pkg/api/api.go#L284

Version v0.11.7

![image](https://user-images.githubusercontent.com/71242762/119923355-1ef75700-bfa4-11eb-8053-0df23e8fb21a.png)

**Comment by sosedoff** [comment]
Yeah you're right, though i don't know what the better UX would be for this functionality: i don't really want to have another button to run explain in the UI.

I suppose this could be achieved with a dropdown-style button that includes `EXPLAIN` / `EXPLAIN ANALYZE` options. Alternatively, we can check if selected query has any write operations (INSERT/UPDATE/etc) and confirm if user wants to perform the operation. 

Thoughts?

**Comment by tim-ings-vgw** [comment]
Thanks for adding this to your 0.12.0 milestone, your suggestion of a dropdown button seems like a good approach to me.

**Comment by sosedoff** [comment]
This one is merger into master already!
