### ISSUE TITLE
Azure Database for PostgreSQL server username contains @, therefore url schema not parsed correctly

### ISSUE THREAD

**Issue by cerginio** [sosedoff/pgweb#519]
Given

After Azure Database for PostgreSQL server creation in Azure, 

Server name:
mycompany-dev-pgsql-srv.postgres.database.azure.com

Admin username:
dba@mycompany-dev-pgsql-srv
usrename contains @ symbol

Password highly likely may contain @ symbol, i.e
passw@rd

URL scheme:
postgresql://dba@mycompany-dev-pgsql-srv:passw@rd1@mycompany-dev-pgsql-srv.postgres.database.azure.com:5432/my_database?sslmode=require

When
In pgweb connect page  'Enter server URL scheme' tab using schema
"postgresql://dba@mycompany-dev-pgsql-srv:passw@rd1@mycompany-dev-pgsql-srv.postgres.database.azure.com:5432/my_database?sslmode=require"

Then
the dialog throws error:
pq: password authentication failed for user "dba"

The same problem with setup URL schema as environment variable for Docker image.

Solution:
Could you please consider one of these:
1. introduce brackets to escape @ symbol in username and password:

postgresql://[dba@mycompany-dev-pgsql-srv]:[passw@rd1]@mycompany-dev-pgsql-srv.postgres.database.azure.com:5432/my_database?sslmode=require

2. %40 support escape symbol for @

postgresql://dba%40mycompany-dev-pgsql-srv:passw@rd1%40mycompany-dev-pgsql-srv.postgres.database.azure.com:5432/my_database?sslmode=require

Maybe your parser supports some other way to user @ within username password parameters in URL schema?

**Comment by skrach** [comment]
I'm also using pgweb to connect to an Azure database. The connection string is in the form `postgres://user@database.database.azure.com:password@database.database.azure.com:5432/databasename` and pgweb connects without problems.

**Comment by sosedoff** [comment]
Im closing this since author did not provide any further information. Feel free to reopen if you have extra input/repro steps/etc.
