### ISSUE TITLE
troubleshooting disconnection

### ISSUE THREAD

**Issue by yashasolutions** [sosedoff/pgweb#523]
Hi,

I have been using pgweb for a year+ now and somehow I have an issue for the past few month i am not able to fix. 
Basically when I run 
```
pgweb --host=195.XXX.XX.XX --port=XXX --user=someuser  --pass=somepass --db=somedb  --auth-user=someauthuser --auth-pass=someauthcode --no-idle-timeout --listen=8086
```

it disconnects automatically after some time (I am unable to pin point any specific duration but between a few hours to 2~3 days).

I have had the problem since march this year when I moved it to docker. Before it was running as a standalone command line with nohup and it was working like a clock with no disconnections unless the server rebooted. 

I took it off docker last week, because I was tired of restarting the container, and I have the same issue now outside of docker...

Was there a new feature introduced at some point to auto disconnect from the DB? Has anyone face a similar issue? How could I get this to stop disconnect from the db?

Thanks!

**Comment by sosedoff** [comment]
Which version are you using?

There's a idle connection cleanup helper in place https://github.com/sosedoff/pgweb/blob/360d7d87c5758cf071e5da68cff27d141fbb69af/pkg/api/session_cleanup.go#L25 but it should not get triggered if you set the `no-idle-timeout` flag or set timeout to 0. 

Could you provide more debug information, like an error message when it disconnects?

**Comment by yashasolutions** [comment]
I am using the latest version
```
Pgweb v0.11.8 (git: 4de356cb1d47d7407169d75a710520c6cd184fb7) (go: go1.16)
```

Regarding logs I wish there was anything significant but nothing I can seem to identify as an error. Here is a sample anyway : [link](https://www.logpasta.com/paste/raw/1bf57649-27f8-4490-8642-8b5f4528b067.txt) (it's from the container log so pgweb is one version earlier, but now I have moved back to command line, logs look the same. I just don't have them available as my script erase the previous logs on restart, I have just fixed that...)

**Comment by yashasolutions** [comment]
ok I have added `--idle-timeout=0` extra to --no-idle-timeout let's see if this stabilize the connection

**Comment by yashasolutions** [comment]
update - it didn't 

trying now to change the timeout to an large number instead.

**Comment by sosedoff** [comment]
ok you'll need to also provide some repro instructions: which postgres version, os, envs, etc you're using so i can test it out and hopefully implement a fix

**Comment by sosedoff** [comment]
Please reopen if you have any extra info. Im just trying to clear out the issue tracker.
