### ISSUE TITLE
404 when running the new docker image

### ISSUE THREAD

**Issue by mablesly** [sosedoff/pgweb#524]
The new docker image causes a 404 when trying to reach pgweb. 

The log seems to be fine: 

```
Pgweb v0.11.8 (git: 4de356cb1d47d7407169d75a710520c6cd184fb7) (go: go1.16)
Connecting to server...
Connected to PostgreSQL 13.3
Checking database objects...
Starting server...
To view database open http://0.0.0.0:8081/ in browser
[GIN] 2021/08/06 - 07:28:21 | 404 |        17.2µs |      172.17.0.1 | GET      /pgweb
[GIN] 2021/08/06 - 07:28:27 | 404 |        16.9µs |      172.17.0.1 | GET      /pgweb/
[GIN] 2021/08/06 - 07:38:14 | 404 |        17.3µs |      172.17.0.1 | GET      /pgweb/api/info
[GIN] 2021/08/06 - 07:38:47 | 404 |        57.9µs |      172.17.0.1 | GET      /pgweb/index.html
```

The log above is the result of running the basic example of the docker wiki. 

Version v0.11.7 has no problems.

This particular test was executed on mac os x, but we also have problems in an ubuntu installation. 

Best regards

**Comment by sosedoff** [comment]
@mablesly def a bug and i was able to reproduce it. it has to do with a switch to standard go embeds that was added in the latest release. i'll get this fixed up. thanks!

**Comment by sosedoff** [comment]
this is fixed in master and should go out in the next release
