### ISSUE TITLE
Write Cursor/Prompt displays on the wrong position on waterfox (possibly also firefox and other mozilla browsers)

### ISSUE THREAD

**Issue by Imeguras** [sosedoff/pgweb#528]
The issue displays itself when im trying to do a query and the cursor/prompt is way too ahead of where the actual position is. 
On the console theres a warning stating 
`This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.`
This however doesn't happen on chromium making me have to use a completely different browser to use it, currently im using Arch linux with OpenBox as the display manager and the version i installed was the 64 bit amd one, although im using a lenovo y520, which comes with integrated intel graphics and nvidia one although i don't believe hardware to be the issue since everything runs smoothly on chromium

This can be hard to explain so heres an image to explain it there are no space's or blank characters in the image, as you can see the cursor/prompt is way ahead of its position
![image](https://user-images.githubusercontent.com/58604146/134817986-27e1f360-b869-4e5a-a2db-e1606206c6de.png)
here is me on the second character position(or the first character, that being the f) as you can see im a bit too offset to the right 
![image](https://user-images.githubusercontent.com/58604146/134818017-f3ebdf1f-9cca-4ce1-badc-996c50cb2005.png)
its "zero" is well set thought heres be on the very first character position
![image](https://user-images.githubusercontent.com/58604146/134818046-d9194617-0c77-4c07-810e-90a48c4ebe3f.png)

**Comment by sosedoff** [comment]
Im not sure if this has something to do with ACE editor being used in Pgweb, or something with your system.
Feel free to reopen if you've got any more information on how to reproduce the issue.
