### ISSUE TITLE
Pgweb logging session id in application logs

### ISSUE THREAD

**Issue by bhupixb** [sosedoff/pgweb#538]
Hi,
We are using pgweb on Kubernetes, pgweb container running as a Pod. We are using pgweb's connect backend feature, we have noticed one thing that is fundamentally a security concern:
-> Whenever you connect to a new db, it creates a session id that is being logged in applications logs, sample:
```
GET  /connect/<connect-token>
GET  /?session=<session-id>
```
Since these logs will be pushed in Elastic Search(in our particular case), anyone can just take your session id and can connect/run queries in db on your behalf which is scary thing that should be avoided. 

Any help or comments on this will be appreciated.

**Comment by sosedoff** [comment]
What do you mean by "anyone" in this case? Are you exposing pgweb to public internets?

**Comment by bhupixb** [comment]
Hi, thanks for the response. "anyone" here means any dev/QA etc from our organization, since ES can be used by any team for viewing logs(we have a shared ES that's used by all teams). Also none of pgweb & ES are on public internet btw.

**Comment by sosedoff** [comment]
Ok, so this is purely internal use case then. Your best bet is to filter out unwanted parameters during the logs ingestion phase (im sensing that you're on ELK stack?). Pgweb is currently using a default Gin logger, so if we want to remove potentially sensitive data from the request logs it'll require a new release. I cant give you any ETA on that at this time.

**Comment by bhupixb** [comment]
Yes, we are on ELK/EFK stack only. Yes our current plan is to filter sensitive logs at ingestion phase only, but logs will still be available in pod logs(but we have restricted access on who can view pod logs in a namespace), however it would be great if we could have a flag(like https://github.com/sosedoff/pgweb/wiki/Usage#cli-options) in a future release based on which it will turn on or off logging that info.
Thanks for the quick response btw.

**Comment by sosedoff** [comment]
Dont think we really need to have another CLI option to do the log filtering - removing any sensitive data from the logs is a good security measurement in general.

**Comment by bhupixb** [comment]
Yes, makes sense.

**Comment by sosedoff** [comment]
Logging of sessions/connect tokens has been fixed in master, and will be available in the next release.
