### ISSUE TITLE
Connect backend redirection is cached, preventing subsequent logins

### ISSUE THREAD

**Issue by Barnabas** [sosedoff/pgweb#542]
Thank you for your good work on Pgweb, Mr. Sosedoff. We certainly appreciate this useful tool. Here's the scenario I thought you'd like to know about.

Here at AwesomeCorp, we set up a custom connect backend for our installation of Pgweb because we use frequently rotated DB secrets. There are static links to the various databases for admin users from the internal dashboard. We encode which service, database, and role to use as comma-separated values in the "connect token", and the custom backend validates the user (it's all behind proxies, custom headers etc.) and looks up the actual DB secret and makes a database URL.

One day an admin user visits `https://pgweb.awesomecorp.com/connect/service-x,db-y,role-z` for the first time, so Pgweb retrieves connection from the backend, creates a new session, and redirects -- no problem so far. Later, the same user clicks on the same connect link. However, since that time the database credential has rotated, or the Pgweb instance has been restarted and the session is gone. User is redirected to the Pgweb login screen no matter what. _The only way they can get past this screen is if they delete their browser cache before clicking on the connect link again._

The reason for this is that the responses to the connect backend are returning status code 301 ([api.go line 132](https://github.com/sosedoff/pgweb/blob/master/pkg/api/api.go#L132)), which browsers cache indefinitely because [that means "Moved permanently"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301). Because the work to establish a new backend connection and session should happen every time, may I suggest that the status code should be either [302 "Found"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) or possibly [307 "Temporary redirect"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307). FWIW, [OAuth servers typically use 302](https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/).

In the meantime, a workaround is for the system that links to Pgweb to include a random cache-busting query string or in the "token".

**Comment by sosedoff** [comment]
Yea it makes sense to switch to 302 HTTP status code

**Comment by sosedoff** [comment]
Change is merged and will be available in 0.12.0 release
