### ISSUE TITLE
How can I handle pgweb with existed go server project

### ISSUE THREAD

**Issue by abc1236762** [sosedoff/pgweb#545]
Like swagger, I can do
```go
func main() {
	e := echo.New()
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.Logger.Fatal(e.Start(":80"))
}
```
and when I open http://localhost/swagger it will show swagger UI.

Can pgweb do like this?
For example:
```go
const databaseURL = "postgresql://postgres:postgres@localhost:5432/postgres"
func main() {
	e := echo.New()
	e.GET("/admin/*", pgweb.HandlerFunc(databaseURL))
	e.Logger.Fatal(e.Start(":80"))
}
```
and when I open http://localhost/admin it will show pgweb UI.

**Comment by sosedoff** [comment]
No, its not possible to mount/mix pgweb with an existing http handler, primarily due to how the code was originally written. It may be possible, but will require a lot of internal changes.
