### ISSUE TITLE
panic: setting PGHOSTADDR not supported

### ISSUE THREAD

**Issue by sb2nov** [sosedoff/pgweb#551]
Pgweb v0.11.10
panic: setting PGHOSTADDR not supported

goroutine 1 [running]:
github.com/lib/pq.parseEnviron.func2(...)
        /workspace/go/pkg/mod/github.com/lib/pq@v1.1.1/conn.go:1808
github.com/lib/pq.parseEnviron({0xc00044a000, 0x5c, 0xabdc35})
        /workspace/go/pkg/mod/github.com/lib/pq@v1.1.1/conn.go:1821 +0xf25
github.com/lib/pq.NewConnector({0xc0003de640, 0x2d})
        /workspace/go/pkg/mod/github.com/lib/pq@v1.1.1/connector.go:56 +0x12a
github.com/lib/pq.DialOpen({0xd0c4d8, 0xc0003c19e0}, {0xc0003de640, 0x48e293})
        /workspace/go/pkg/mod/github.com/lib/pq@v1.1.1/conn.go:270 +0x37
github.com/lib/pq.Open(...)
        /workspace/go/pkg/mod/github.com/lib/pq@v1.1.1/conn.go:265
github.com/lib/pq.(*Driver).Open(0xa080e0, {0xc0003de640, 0x2d})
        /workspace/go/pkg/mod/github.com/lib/pq@v1.1.1/conn.go:48 +0x7a
database/sql.dsnConnector.Connect(...)
        /home/gitpod/go/src/database/sql/sql.go:761
database/sql.(*DB).conn(0xc000409450, {0xd12110, 0xc000132000}, 0x1)
        /home/gitpod/go/src/database/sql/sql.go:1364 +0x7ac
database/sql.(*DB).query(0x114cc00, {0xd12110, 0xc000132000}, {0xabc19f, 0x10}, {0x0, 0x0, 0x0}, 0x1)
        /home/gitpod/go/src/database/sql/sql.go:1695 +0x5d
database/sql.(*DB).QueryContext(0x4f442d, {0xd12110, 0xc000132000}, {0xabc19f, 0x10}, {0x0, 0x0, 0x0})
        /home/gitpod/go/src/database/sql/sql.go:1674 +0xdf
database/sql.(*DB).Query(...)
        /home/gitpod/go/src/database/sql/sql.go:1691
github.com/jmoiron/sqlx.(*DB).Queryx(0xc0004114d0, {0xabc19f, 0xcf9548}, {0x0, 0x0, 0x0})
        /workspace/go/pkg/mod/github.com/jmoiron/sqlx@v0.0.0-20180614180643-0dae4fefe7c0/sqlx.go:353 +0x55
github.com/sosedoff/pgweb/pkg/client.(*Client).query(0xc0003ea580, {0xabc19f, 0x10}, {0x0, 0x0, 0x0})
        /workspace/go/pkg/mod/github.com/sosedoff/pgweb@v0.11.10/pkg/client/client.go:375 +0x499
github.com/sosedoff/pgweb/pkg/client.(*Client).setServerVersion(0xc0003ea580)
        /workspace/go/pkg/mod/github.com/sosedoff/pgweb@v0.11.10/pkg/client/client.go:146 +0x35
github.com/sosedoff/pgweb/pkg/client.New()
        /workspace/go/pkg/mod/github.com/sosedoff/pgweb@v0.11.10/pkg/client/client.go:81 +0x23e
github.com/sosedoff/pgweb/pkg/cli.initClient()
        /workspace/go/pkg/mod/github.com/sosedoff/pgweb@v0.11.10/pkg/cli/cli.go:79 +0xd8
github.com/sosedoff/pgweb/pkg/cli.Run()
        /workspace/go/pkg/mod/github.com/sosedoff/pgweb@v0.11.10/pkg/cli/cli.go:228 +0x33
main.main()
        /workspace/go/pkg/mod/github.com/sosedoff/pgweb@v0.11.10/main.go:8 +0x1

**Comment by sosedoff** [comment]
That's an issue with pgweb's dependency `github.com/lib/pq` so i recommend reporting the issue there.
