### ISSUE TITLE
Serialize binary bytea cols into hex/base64 does not work correctly on non-ascii characters

### ISSUE THREAD

**Issue by webus** [sosedoff/pgweb#552]
Hi. I noticed that after the last change in version 0.11.10 are not correctly displayed characters that are not included in ASCII. Probably they are recognized as hex/base64 content which is wrong.

Example:
```
SELECT 'Привет' as col1;
```
returns:
```
0J/RgNC40LLQtdGC
```

**Comment by sosedoff** [comment]
Fixed in latest 0.11.11 release
