### ISSUE TITLE
DELETE with RETURNING goes not give the returned rows, just a summary?

### ISSUE THREAD

**Issue by jonaz** [sosedoff/pgweb#553]
The problem seems to be here?
https://github.com/sosedoff/pgweb/blob/706caa44bfda2261681d81ed5fcc01394a95db00/pkg/client/client.go#L354-L373

**Comment by sosedoff** [comment]
Thanks for the report. Do you have an example query?

**Comment by jonaz** [comment]
`DELETE from asdf where id=1 RETURNING id`
