### ISSUE TITLE
Could you please consider setting the default value of the `--binary-codec` option to `none`?

### ISSUE THREAD

**Issue by knowledgecode** [sosedoff/pgweb#554]
Could you please consider setting the default value of the `--binary-codec` option to `none` for non-English speaking users? 

For example, if I insert the following CJK code string and then reference it in `pgweb`, it will be converted to base64 and become unreadable.

```sql
INSERT INTO translations(english, japanese) VALUES('sushi', '寿司');

-- 寿司 => 5a+/5Y+4Cg==
```

Of course I know that this behavior can be disabled by changing the option, but it is a bit inconvenient for non-English speaking users.

**Comment by sosedoff** [comment]
Yep, i realized that a default codec encoding feature was released too fast, so it'll be fixed in the next version.

**Comment by kohama66** [comment]
hello！Let me ask you a question
When will it be reflected in docker image?

**Comment by sosedoff** [comment]
Latest docker image has been published. v0.11.11
