### ISSUE TITLE
Make query editor resizable in height

### ISSUE THREAD

**Issue by stijntratsaertit** [sosedoff/pgweb#563]
This would make it convenient for reading/writing large queries or multiple smaller ones. See the small draggable corner in the bottom left in the image below for example. You could then click and drag this down/upwards to increase or evidently decrease the size of the query editor.
![Screenshot from 2022-06-02 10-34-32](https://user-images.githubusercontent.com/48105356/171589700-8082f619-8294-45d7-b8f9-d26c7f29c531.png)

**Comment by sosedoff** [comment]
Resizing is implemented in master (hover over the query box border and drag to change the size). Will ship in 0.12.0
