### ISSUE TITLE
Add Secure Mode support for Cockroach DB

### ISSUE THREAD

**Issue by abhijit-kar** [sosedoff/pgweb#573]
Hi Team,

I used the pgweb project locally to navigate data added to my Cockroach DB instance locally.

Then I decided to add SSL to everything, so as to bring production parity to development. (To figure out what will work and what won't when I do deploy to prod!!).

I gave a cool sub domain, using etc/hosts, to pgweb, like: pgweb.customdomain.site!!

Alas after doing the dance of securing the Cockroach DB locally, I couldn't figure out how to connect pgweb to the secured version!

I need a way to pass the ca cert file, user cert file, and user private key. (Perhaps env variables can be added for ease of use!)

P.S. Something like the Cockroach SQL:
- cockroach sql --certs-dir=certs/cockroach_db --user=root --host=localhost:26257

**Comment by sosedoff** [comment]
Does any of these parameters work? https://www.cockroachlabs.com/docs/v22.1/connection-parameters#additional-connection-parameters

**Comment by abhijit-kar** [comment]
@sosedoff,

I will give all of those a try. I only tried few of them.

**Comment by abhijit-kar** [comment]
```elixir
pgweb --url "postgres://root@localhost:26257/roach
?sslmode=verify-ca
&sslcert=certs/cockroach_db/client.root.crt
&sslkey=certs/cockroach_db/client.root.key
&sslrootcert=certs/cockroach_db/ca.crt
&password=wubalubadubdub
&cluster=roach-infestation"
```

I was missing the Quotes for the url, that's why it was breaking.

PgWeb works amicably, and connects to Cockroach DB running in secure mode.
