### ISSUE TITLE
bit.io support 

### ISSUE THREAD

**Issue by anaschaudhary33** [sosedoff/pgweb#574]
While using bit.io
Getting this error 
```
pq: inet_client_addr is not supported
```

**Comment by sosedoff** [comment]
I havent used `bit.io` so dont know much about how its configured. Could you provide some context on what you're doing and how you're connecting to their endpoints?

**Comment by anaschaudhary33** [comment]
I am able to connect through psql this using url scheme
```
postgresql://username:password@db.bit.io/databasename
```

the databasename contains a slash 
```databasename=abcd/efgh```

**Comment by sosedoff** [comment]
Not sure what the problem is then. Im going to close unless you have anything else to share

**Comment by Davincible** [comment]
@anaschaudhary33 try url encoding the database name

**Comment by anaschaudhary33** [comment]
> @anaschaudhary33 try url encoding the database name

Tried url encoding ```database%2Fname``` but getting same error
