### ISSUE TITLE
schema evolution tooling

### ISSUE THREAD

**Issue by gedw99** [sosedoff/pgweb#575]
For blue / green deployments, you need to make sure that you dont break your old versions.

In other words, you never rename a field in a table, and other rules like this.

Conceptually is almost exactly what you have to do higher up in the stack with GRPC and Protocol Buffers. Buff is a tool in golang that does this for you with linting checkers. https://github.com/bufbuild/buf

It would be really cool is pgweb had some of these concepts 

Another tool is Atlas at https://github.com/ariga/atlas. It supports Schema migration

**Comment by sosedoff** [comment]
While i appreciate your links, pgweb does not manage any schemas or table contents, so it's got nothing to do with such tools.

**Comment by gedw99** [comment]
got it. Will see if i can use atlas for it. thanks
