### ISSUE TITLE
password visible to everyone?

### ISSUE THREAD

**Issue by f1-outsourcing** [sosedoff/pgweb#578]
You do know that supplying the password as command line argument is visible to every one? Lots of containers work with supplying configuration via environment variables

**Comment by sosedoff** [comment]
@f1-outsourcing what exactly do you mean by `every one`?

Also, see https://github.com/sosedoff/pgweb/wiki/Usage#environment-variables-available for environment variables supported by the application

**Comment by f1-outsourcing** [comment]
I am blind! Totally missed this page. Everyone that can query the host ps, and some container orchestrators publish this type of information in rest end points.

**Comment by sosedoff** [comment]
Gotcha - keep in mind pgweb is not meant to be run in untrusted environments, its a tool that does not have many control knobs so if you're concerned with security (ie people seeing prod credentials) - do not run pgweb on such hosts. 

I'll make a note of `--help` modifications, thank you.

**Comment by sosedoff** [comment]
This was added in #586
