### ISSUE TITLE
CSV Exports failing when running PGWeb behind SSO

### ISSUE THREAD

**Issue by tomellis91** [sosedoff/pgweb#587]
Hi There, 

We have placed PGWeb behind an SSO Authentication system. 

When navigating to PGWeb via SSO it appends a token to the end of the URL string 

eg. `pgweb.example.com/?code=xyz`

When hitting the export CSV button a new window opens with an invalid url which means the download is unable to proceed
Example output url : `pgweb.example.com/?code=xyzapi/query?format=csv...`

I believe the issues is coming from this [line here](https://github.com/sosedoff/pgweb/blob/13091c2a7cab571adac0c1ef5343da76793abe90/static/js/app.js#L763). 

Is it possible to get the URL to take into account additional Query params when redirecting to the download screen?

**Comment by sosedoff** [comment]
Hi @tomellis91, yes def possible. What kind of SSO are you running in front of pgweb?

**Comment by tomellis91** [comment]
Amazing, thanks @sosedoff . 

We are using oauth2 with an authorization code grant. 

Cheers, 
Tom

**Comment by sosedoff** [comment]
Cool, i will have a look. Mind sharing details on how you run pgweb and oauth? This is one of core features missing from pgweb and i would like to incorporate it somehow.On Nov 28, 2022, at 6:07 PM, Tom Ellis ***@***.***> wrote:﻿
Amazing, thanks @sosedoff .
We are using oauth2 with an authorization code grant.
Cheers,
Tom
