### ISSUE TITLE
v0.11.12 Introduced 32 new critical vulnerabilities 

### ISSUE THREAD

**Issue by vgw-courtney-m** [sosedoff/pgweb#598]
As of 1.11.12, the amount of critical vulnerabilities went up from 1 to 33.

Trivy report: 

12: https://trivy.dev/results/?image=sosedoff/pgweb:0.11.12
11: https://trivy.dev/results/?image=sosedoff/pgweb:0.11.11

**Comment by sosedoff** [comment]
That's due to the Dockerfile base image swap from alpine to debian:buster-slim: https://trivy.dev/results/?image=debian:buster-slim. Upcoming 0.12.0 release will incorporate latest debian image and fix all these errors (where applicable)
