### ISSUE TITLE
URL Parameter Required with latest Version but everything is filled in

### ISSUE THREAD

**Issue by Alfagun74** [sosedoff/pgweb#630]
![image](https://user-images.githubusercontent.com/22225051/209740096-5e5feb02-5639-49d1-a084-ac1535596af0.png)

As you can see i filled in everything but it still wont connect, it worked with version 0.11.12 though.

**Comment by Alfagun74** [comment]
broken since 0.12.0

**Comment by sosedoff** [comment]
Could you check which params are being sent in the browser? (open up dev console and check on xhr calls being made from pgweb)

**Comment by sosedoff** [comment]
Nvm, i reproduced this locally.

**Comment by Alfagun74** [comment]
was just about to shoot, but alright, thank you for the fast reaction!

**Comment by sosedoff** [comment]
This is only an issue when `~/.pgweb/bookmarks` directory does not exist. I'll cut a new version with a fix

**Comment by sosedoff** [comment]
Fix will go out in 0.13.1
