### ISSUE TITLE
create a brew service 

### ISSUE THREAD

**Issue by shivshankar3578** [sosedoff/pgweb#643]
Good work
Looking for a brew service. It looks easy as I'm following this example https://apple.stackexchange.com/questions/293163/how-do-i-add-tomcat-to-brew-services

**Comment by sosedoff** [comment]
I think this belongs in the `homebre-core` repo: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgweb.rb
Example service https://github.com/Homebrew/homebrew-core/blob/master/Formula/redis.rb#L42-L48.

I do not maintain the `pgweb` formula updates, so if you'd like to see the `service` support in Pgweb, you're welcome to provide the implementation.
