### ISSUE TITLE
Is there any plans for adding a form for easy inserting data into table?

### ISSUE THREAD

**Issue by anton-okolelov** [sosedoff/pgweb#651]
Thanks for pgweb, it looks very well!

But unfortunately, a key feature is missing: adding data to a table without writing an SQL query. If that feature existed I could use it for our QA engineers in our testing environment.  Also, we need "edit" button on rows (instead writing UPDATE queries).

**Comment by sosedoff** [comment]
No plans for row-level data management in v0.x line. Plus, v1 work is not even planned, so you're basically better off using something else if you wish to edit data. TablePlus is a great cross-platform alternative.
