### ISSUE TITLE
Feature request: text overflow UX improvements

### ISSUE THREAD

**Issue by Davincible** [sosedoff/pgweb#653]
When there is a large text body in a column now, there is no way to see the full text except inspect the HTML element. It would be nice to be able to see the full text. I have some solutions in mind, each its own feature. Having all of them would be amazing, but just one is a good start

### Text popup on hover
It would be nice to have the full text in a little pop-up when you hover over overflowing columns.

### Resizeable columns when you drag the column border
I know this isn't a small feature and probably not very easy, but would be very cool to have

### Auto horizontally size rows
Auto-increase the row height if not all columns fit. But only behind an option, also not nice to always have this. Maybe behind a right mouse click option, "expand row", "expand all rows"

**Comment by sosedoff** [comment]
You can double click on a cell and a popup with the full cell content will appear, does that work for you?

**Comment by Davincible** [comment]
@sosedoff double clicking does nothing for me, both firefox and chromium

**Comment by sosedoff** [comment]
Which version are you on? This is a recently added feature so give pgweb v0.14 a try.

**Comment by sosedoff** [comment]
@Davincible did that work out for you in the end?

**Comment by Davincible** [comment]
No, still doesn't seem to work

**Comment by Davincible** [comment]
Ah now it does work!
