### ISSUE TITLE
Documentation for hosting pgweb in cloudrun

### ISSUE THREAD

**Issue by anovis** [sosedoff/pgweb#655]
First off great project. I was able to host pgweb in GCP's Cloudrun with a connection to Cloudsql using a [cloudsql connector](https://cloud.google.com/sql/docs/postgres/connect-auth-proxy#other-platforms). This took me way too long, but think this is a great use case that I would like to share back. Would you like me to add a pr to the readme adding some info or add something to the wiki. 

Essentially I was able to host a completely serverless solution on GCP in Cloudrun ([super cheap](https://cloud.google.com/run/pricing)) and used IAP for the auth layer.

I am also planning on writing a quick blog on medium, so could always just link there.

**Comment by sosedoff** [comment]
I currently disabled WIKI edits to collaborators only due to rogue edits. 
If you have a writeup - you can submit it in here with a link to your gist (or whatever).

**Comment by sosedoff** [comment]
Added https://github.com/sosedoff/pgweb/wiki/Community-Resources
