### ISSUE TITLE
add a convenient menu for editing the table

### ISSUE THREAD

**Issue by OmlineEditor** [sosedoff/pgweb#665]
please add the ability to edit the data in the table and the table itself in a convenient way. Now it is possible only through the console, it is inconvenient. Using the menu in a more convenient graphical form is good. I hope this handy feature will appear in the new
version.

**Comment by sosedoff** [comment]
No data/schema editing functionality is planned for v0 branch of this project. Next version will have it, but i can't comment on any timeframes right now.
