### ISSUE TITLE
BinaryCodec default config is base64

### ISSUE THREAD

**Issue by dszy0312** [sosedoff/pgweb#672]
![image](https://user-images.githubusercontent.com/13452998/234236754-c4f4d73b-1d61-4236-b0be-0c4a070bdbfb.png)

![image](https://user-images.githubusercontent.com/13452998/234237102-3830c6b5-d474-4e24-ade6-35710144b437.png)

Please ensure that the comments in the configuration file are consistent with the actual variable configuration.

**Comment by sosedoff** [comment]
The default is `none`, like the CLI options state, because when the app starts we set the codec values from the argument.

**Comment by sosedoff** [comment]
I updated the comment in master though, for clarity sake

**Comment by dszy0312** [comment]
But if the parameter is not set, the default value will not automatically be set to 'none'. According to the code, in this case the default value will be 'base64'.
![image](https://user-images.githubusercontent.com/13452998/234465343-fdeae8d4-7466-4db1-beda-c3ceb582145a.png)
