### ISSUE TITLE
No bookmarks after update from docker image 0.14.0 to 0.14.1

### ISSUE THREAD

**Issue by andrew-jones** [sosedoff/pgweb#682]
Hi,

We updated pgweb to 0.14.1 and the bookmarks dropdown is no longer available.  No config changes, is there something we need to do?

Thanks

**Comment by sosedoff** [comment]
Hey @andrew-jones, could you check the logs? Could be related to the user swap in the docker image.

**Comment by andrew-jones** [comment]
Yeah looks like it, we are mounting `mountPath: /root/.pgweb/bookmarks`.  WIll change the mount path.

Logs:

`[WARN] bookmarks dir /home/pgweb/.pgweb/bookmarks does not exist`
