### ISSUE TITLE
Is Debug build for Win release (and all other)?

### ISSUE THREAD

**Issue by Quake4** [sosedoff/pgweb#710]
Win binary size huge increase in 0.14.3 (up to 7 Mb)!

![image](https://github.com/sosedoff/pgweb/assets/29517243/0f945fff-4afe-4864-b2a1-9e1f1596e2bc)

**Comment by Quake4** [comment]
0.14.3
![image](https://github.com/sosedoff/pgweb/assets/29517243/7bc422fb-a7bc-4782-ba7e-002845b51653)

0.14.2
![image](https://github.com/sosedoff/pgweb/assets/29517243/b39b0a96-ff2f-4e6f-a635-27816ae06c63)

**Comment by sosedoff** [comment]
This is fixed in the latest release.
