### ISSUE TITLE
Broken paging on ROWS tables view

### ISSUE THREAD

**Issue by Quake4** [sosedoff/pgweb#720]
![image](https://github.com/sosedoff/pgweb/assets/29517243/2031e558-5b81-4f95-aca2-cbd49e62a328)

**Comment by sosedoff** [comment]
Is there anything else you can share about the "broken view"? The screenshot alone does not give me much info your issue.

**Comment by Quake4** [comment]
Must be a around 1000 rows on page, now 30k on page is too much.

**Comment by sosedoff** [comment]
Not sure whats going on tbh, maybe we can try to narrow this down. Could you try:

1. Right-click on the database name (top-left) and select "Show tables stats". This should display list of all your tables and their stats (estimated number of rows) so you can confirm size of the table in question.
2. Click on the pagination button when you browse table rows. It will open up a modal with current pagination setting. Default is 100, but maybe you have a different value set.

<img width="278" alt="Screenshot 2024-03-22 at 7 10 21 PM" src="https://github.com/sosedoff/pgweb/assets/71051/46312b80-ff76-41a8-9df9-931f57597273">

<img width="583" alt="Screenshot 2024-03-22 at 7 13 16 PM" src="https://github.com/sosedoff/pgweb/assets/71051/71234685-ef44-4cab-9f6b-96ef68b86893">

**Comment by Quake4** [comment]
sorry, working...
