### ISSUE TITLE
Pod says completed

### ISSUE THREAD

**Issue by jagar2** [sosedoff/pgweb#722]
I have been trying to run pgweb and for some reason on k8s after a while it will say completed, and is no longer running. I cannot seem to find a setting, but it seems strange that a web server would have a timeout.

**Comment by sosedoff** [comment]
@jagar2 How are you running pgweb in k8s? Single configuration or in sessions mode?
Any additional info on your setup will help me troubleshoot.

Since you mention "after a while", i could suspect the idle timeout closing the session due to inactivity, which is configured via options:

```
--no-idle-timeout     Disable connection idle timeout
--idle-timeout=       Set connection idle timeout in minutes (default: 180)
```

**Comment by sosedoff** [comment]
Closing for now. Feel free to reopen if the issue persists.
