### ISSUE TITLE
Support for libpq-standard PG env-vars

### ISSUE THREAD

**Issue by ddevienne** [sosedoff/pgweb#723]
I used [service][2] and [password][1] files, and sometimes other [env-vars][3] as well. to connection to PostgreSQL (v12, v14, v16).

Which work fine for my own native exes (since libpq-based, C++) and also with `psql`.

`pgweb` looks really interesting to me, but having to use different CLI args or env-vars to connect, would be _inconvenient_.

So does `pgweb` support libpq-standard env-vars?
And if not, any chance it might in the future?

Thanks, --DD

PS: Since `pgweb` is _no-dependencies_, I assume it uses a Go-native client implementation instead of `libpq`.

[1]: https://www.postgresql.org/docs/16/libpq-pgpass.html
[2]: https://www.postgresql.org/docs/16/libpq-pgservice.html
[3]: https://www.postgresql.org/docs/current/libpq-envars.html

**Comment by sosedoff** [comment]
Pgweb does not aim to support native Postgres configuration values, and it uses the native Go package for interactions with Postgresql (there may be some overlap in env var names, but it minimal).

Please refer to https://github.com/sosedoff/pgweb/wiki/Usage for configuration options (or `pgweb --help`)

**Comment by ddevienne** [comment]
Bummer. OK, thanks.
