### ISSUE TITLE
does it support clickhouse ? 

### ISSUE THREAD

**Issue by akshaytaywadephilips** [sosedoff/pgweb#734]
can you tell the steps to connect to clickhouse

**Comment by akshaytaywadephilips** [comment]
@sosedoff  can you please help

**Comment by akshaytaywadephilips** [comment]
in pgweb

**Comment by sosedoff** [comment]
Clickhouse is not currently supported by PgwebOn May 9, 2024, at 2:30 AM, akshaytaywadephilips ***@***.***> wrote:﻿
in pgweb

**Comment by akshaytaywadephilips** [comment]
@sosedoff  if we want to implement clickhouse what changes we have to do ? can you please help in this regard

**Comment by sosedoff** [comment]
Im not familiar with Clickhouse so i don't have any advice on how to implement the support. Why do you need it in the first place?

**Comment by sosedoff** [comment]
Closing this for now
