### ISSUE TITLE
Missing Docker image for 0.16.0

### ISSUE THREAD

**Issue by rouge8** [sosedoff/pgweb#741]
https://github.com/sosedoff/pgweb/pkgs/container/pgweb hasn't been updated for 0.16.0

**Comment by sosedoff** [comment]
Yes, it appears that the release flow is broken. I will try to fix it todayOn Jun 5, 2024, at 10:11 AM, Andy Freeland ***@***.***> wrote:﻿
https://github.com/sosedoff/pgweb/pkgs/container/pgweb hasn't been updated for 0.16.0

**Comment by Alfagun74** [comment]
the v0.16.0 is still not available on Docker.

**Comment by sosedoff** [comment]
Yes, unfortunately i did not have any spare time to get to the bottom of this.

**Comment by sosedoff** [comment]
Unfortunately no update on this yet. I think since a few more changes were merged in, it would be easier to release 0.16.1 instead, which will have all the needed binary artifacts in place.

**Comment by wajeht** [comment]
+1

**Comment by sosedoff** [comment]
If 0.16.0 is still needed, you can grab it here: https://hub.docker.com/layers/sosedoff/pgweb/0.16.0-20240907/images/sha256-2fb4a9ce91aef739d3169b89ae1d782d6b2a37d8e96adaf26d1fddaf0c342628?context=explore (its a date-tagged 0.16.0 release)

Also 0.16.1 has been published and available in both Docker Hub and GHCR
