### ISSUE TITLE
Support of latest PostgreSQL versions

### ISSUE THREAD

**Issue by sskserk** [sosedoff/pgweb#745]
Dear PgWeb Developers,

thank you for an amazing product. It really helps a lot.

Do you have any plans to support the latest PostgreSQL version?

I'm referring the content of the next file -> https://github.com/sosedoff/pgweb/blob/master/pkg/statements/sql.go

Thank you!

**Comment by sosedoff** [comment]
Pgweb supports the latest version 16 of Postgresql

**Comment by sskserk** [comment]
Thank you!
