### ISSUE TITLE
Alternative format of log messages

### ISSUE THREAD

**Issue by sskserk** [sosedoff/pgweb#746]
Dear PgWeb Developers,

is it possible to change the format a log messages?  I guess it is fixed for now and is simply based on the fmt.Println

Thank you!

**Comment by sosedoff** [comment]
No, the log format is pretty fixed. What is that you're looking to add to the log?

**Comment by sskserk** [comment]
In my use case I have a requirement to change the logging level. For instance, SQL queries could be logged in trace or debug level, but not as INFO.
SQL queries contains parameters, that information could be sensitive.

The application is already dockerized, it would be beneficial to have the log level and format configurable with the env vars.

**Comment by sosedoff** [comment]
Take a look at CLI options here: https://github.com/sosedoff/pgweb/wiki/Usage#cli-options, you may find what you're looking for after all. You can configure the log level and format (json/text).
