### ISSUE TITLE
No execution time on `No records found` requests.

### ISSUE THREAD

**Issue by Quake4** [sosedoff/pgweb#755]
![image](https://github.com/user-attachments/assets/394b6c3e-1530-4054-876f-faddeda5078f)

**Comment by Quake4** [comment]
It is necessary to show the execution time, why is it hidden?

**Comment by istiak101** [comment]
If you believe it is trivial just send a patch.

**Comment by Quake4** [comment]
its trivial
app.js: buildTable

```js
  if (results.rows.length == 0) {
    $("#results_header").html("");
    $("#results_body").html("<tr><td>No records found</td></tr>");
    $("#result-rows-count").html("");
    $("#results").addClass("empty");
    if (results.stats)
      $("#result-rows-count").html(results.stats.query_duration_ms + " ms");
    return;
  }
```

**Comment by sosedoff** [comment]
If it's so trivial, why don't you open up a proper PR with the change you'd like to see?

**Comment by Quake4** [comment]
https://github.com/sosedoff/pgweb/pull/763

**Comment by sosedoff** [comment]
Closing the issue since the requested change has been implemented and merged into `main`.
