### ISSUE TITLE
Use pg_service.conf for authentication

### ISSUE THREAD

**Issue by fin-gal** [sosedoff/pgweb#757]
Hi there,

when using psql, I regularly use the pg_service.conf service file for faster authentication. Instead of providing everytime the host, username, db name and even pass, one can store in the conf these details along with a service name and then connect using that service name.

Is it something that would be possible/reasonable to also leverage the same file for connection using pgweb? Or is this too much effort for not much benefit?

**Comment by sosedoff** [comment]
I would say its not worth the trouble of making pgweb compatible with pg-native tooling

**Comment by fin-gal** [comment]
@sosedoff 
Hi there,

I feel like since you've already implemented leveraging the pg .passfile, pgweb is already compatible with some pg-native tooling no?
To parse the passfile you're using a libary [developed by jackc](https://github.com/jackc/pgpassfile). He also implemented a similar library [for pgservice files](https://github.com/jackc/pgservicefile).

If you agree I'd be happy to implement the use of it in pgweb, get it working for different platforms, test it and make a PR.

**Comment by sosedoff** [comment]
I personally do not use `passfile` functionality these days, so can't event comment on the use of `pg_service`. Im not totally against implementing it in pgweb, but i would prefer if someone who's more familiar with that servicefile feature come up with a clean implementation. 

If you have a PR with working version (and some tests), then i can take a look and maybe test drive it given you provide all necessary information for testing.
