### ISSUE TITLE
Feature Request: Inline editing of records

### ISSUE THREAD

**Issue by 54keesh** [sosedoff/pgweb#759]
Hats off to the creator, its a great tool, tho one feature might be a plus.

While double clicking a row currently opens up a modal with column value inside of it, it should be editable and when the modal is closed or a save button is pressed, the editted column value gets updated in the record.

This way one doesnt have to manually go to the query tab and write an explicity update query.

**Comment by sosedoff** [comment]
Yea the inline record editing feature has been requested on numerous occasions, but i don't think i have any bandwidth to implement it in the current scope of pgweb project.

**Comment by 54keesh** [comment]
Do you accept PRs? If so I would like to raise a PR for this feature. 
Could you then please reopen this issue?

**Comment by 54keesh** [comment]
@sosedoff PRs not possible ?

**Comment by sosedoff** [comment]
That would heavily depend on the overall execution.
