### ISSUE TITLE
Uppercase table names must be quoted

### ISSUE THREAD

**Issue by joshstrange** [sosedoff/pgweb#77]
This may be connected to both #29 and #16 (if not the same issue). I have a table that starts with a capital letter (eg: "Users") and if I try to do a query 'SELECT * FROM Users' it complains about there being no "users" table. However if I do 'SELECT * FROM "Users"' then it works.

I don't have a lot of experience with pgsql (come from a mysql background) and I rarely use uppercase in my table names (the ORM I'm using did it). The structure tab works just fine, it's just queries that are effected. Again, this may be expected behavior but I wanted to open an issue to make sure. Thanks!

**Comment by sosedoff** [comment]
Which pgweb version are you using? Also on which OS ?

**Comment by lfx** [comment]
Hello, @joshstrange I think this may be your case http://blog.lerner.co.il/quoting-postgresql/

**Comment by sosedoff** [comment]
Closing this issue unless there's a problem. No feedback received.
