### ISSUE TITLE
Run query for selected text

### ISSUE THREAD

**Issue by brian-vogogo** [sosedoff/pgweb#78]
When text is selected, only run the selected text as a query. Otherwise use the current behaviour, and run all entered text as a query.

I use the query tab as a scratchpad - adding queries or editing old ones as I navigate a problem. Currently I will comment out all other sql statments, run the query then comment it out and uncomment a different sql statement.

**Comment by sosedoff** [comment]
I dont think this is a big deal. If you're doing lots of prototyping this is the cost you've gotta pay.
Imaging doing prototyping using a plain-old `psql`, you cant just "select" a query and run it. So unless you have any code to support that i wont be working on this.

**Comment by brian-vogogo** [comment]
Yeah I agree. Meant this is a minor feature suggestion. If you are open to a pull request I can get it going. If not, no worries - thanks for a great tool.

**Comment by sosedoff** [comment]
Im alway open for a good PR!
