### ISSUE TITLE
Bookmark.Port expected string.

### ISSUE THREAD

**Issue by KenjiTakahashi** [sosedoff/pgweb#80]
According to [wiki](https://github.com/sosedoff/pgweb/wiki/Server-Connection-Bookmarks), port in bookmark file should be int, but it fails with

`
Type mismatch for 'main.Bookmark.Port': Expected string but found 'int64'.
`

Passing it as string instead works fine.
Either wiki is wrong or code is wrong :-).

**Comment by sosedoff** [comment]
Thanks for reporting. I will check.

**Comment by sosedoff** [comment]
All bookmark attributes should be encoded as strings, i corrected the wiki page. Thanks!
