### ISSUE TITLE
UI: Moving from SQL Query to Structure leaves query editor on screen.

### ISSUE THREAD

**Issue by KenjiTakahashi** [sosedoff/pgweb#81]
Steps to reproduce:

1. Choose a table.
2. Choose SQL Query.
3. Choose Structure.

Query editor stays on the screen. Moving to some other tab and back to Structure fixes it.

**Comment by sosedoff** [comment]
Thanks, i'll fix it.

**Comment by sosedoff** [comment]
This is fixed in master.
