### ISSUE TITLE
v0.6.0 OSX (amd64) broken

### ISSUE THREAD

**Issue by tcn** [sosedoff/pgweb#86]
Hi!

Two obvious issues:

1) the 0.6.0 tarball's binary reports: Pgweb v0.5.2 (git: 79bf430dee865dbd2be65e7b95a16332f64e826c)
2) Asset static/index.html can't read by error: Error reading asset static/index.html at /Users/sosedoff/Go/src/github.com/sosedoff/pgweb/static/index.html: open /Users/sosedoff/Go/src/github.com/sosedoff/pgweb/static/index.html: no such file or directory

And the actual 0.5.2 silently doesn't list any tables on the left (pg 9.4.2).

**Comment by sosedoff** [comment]
Hi @tcn,

Thanks for your report. Im aware of 0.6.0 version issue and will fix soon.
Regarding the second issue, i think this might have been a problematic binary build.. I'll need to redo it
to fix the problem. 

What about the empty tables list ? Do you see any errors in the console? Alternatively you could run a direct request against api: GET http://localhost:808(or 8081)/api/tables

**Comment by tcn** [comment]
Hey,

Nope, console LGTM. Here's the complete output (incl. the GET which returns "[]"):

```
$ ./pgweb_darwin_amd64 --user foo --host localhost --db foo --pass foo
Pgweb version 0.5.2
Connecting to server...
Checking tables...
Starting server...
To view database open http://localhost:8080 in browser
[GIN] 2015/06/05 - 17:49:27 | 200 |    237.966µs | 127.0.0.1:63115 |   GET     /
[GIN] 2015/06/05 - 17:49:28 | 200 |  33.348966ms | 127.0.0.1:63117 |   GET     /static/css/font-awesome.css
[GIN] 2015/06/05 - 17:49:28 | 200 |  20.655069ms | 127.0.0.1:63115 |   GET     /static/css/app.css
[GIN] 2015/06/05 - 17:49:28 | 200 |  20.550049ms | 127.0.0.1:63119 |   GET     /static/css/bootstrap.css
[GIN] 2015/06/05 - 17:49:28 | 200 |  17.738562ms | 127.0.0.1:63121 |   GET     /static/js/jquery.js
[GIN] 2015/06/05 - 17:49:28 | 200 |  15.190712ms | 127.0.0.1:63123 |   GET     /static/js/ace.js
[GIN] 2015/06/05 - 17:49:28 | 200 |   5.865284ms | 127.0.0.1:63125 |   GET     /static/js/ace-pgsql.js
[GIN] 2015/06/05 - 17:49:28 | 200 |    368.272µs | 127.0.0.1:63117 |   GET     /static/js/app.js
[GIN] 2015/06/05 - 17:49:28 | 200 |   1.541463ms | 127.0.0.1:63123 |   GET     /api/connection
[GIN] 2015/06/05 - 17:49:28 | 200 |    1.32848ms | 127.0.0.1:63123 |   GET     /api/tables
[GIN] 2015/06/05 - 17:49:28 | 200 |   1.871071ms | 127.0.0.1:63123 |   GET     /static/fonts/fontawesome-webfont.woff
[GIN] 2015/06/05 - 17:49:42 | 200 |   1.413779ms | 127.0.0.1:63123 |   GET     /api/tables
[GIN] 2015/06/05 - 17:49:42 | 404 |         86ns | 127.0.0.1:63123 |   GET     /favicon.ico
```

**Comment by sosedoff** [comment]
Do you have any tables in public schema ?

**Comment by tcn** [comment]
No, the tables are actually in a dedicated schema. Found no way to specify it, though.

**Comment by sosedoff** [comment]
I see. Yeah, right now pgweb only supports public schema but im working on having multiple schema support as well. Dont know ETA, but hopefully in the next version or two.

**Comment by sosedoff** [comment]
@tcn could you please try https://github.com/sosedoff/pgweb/releases/tag/v0.6.1 binary ?

**Comment by RobertAudi** [comment]
@sosedoff I just tried `v0.6.1`. Seems to work. But at first I installed pgweb via `brew cask install pgweb`, which installed `v0.5.2`, and I encountered the same problem.

**Comment by sosedoff** [comment]
There was an issue with binary packaging that i did not notice so i'll have more clean build process in the future. If 0.6.1 works fine i'll go ahead and push that to homebrew.

**Comment by sosedoff** [comment]
0.6.1 is released to homebrew cask repo
