### ISSUE TITLE
schema prefix `postgresql://`

### ISSUE THREAD

**Issue by tylerlong** [sosedoff/pgweb#88]
`postgresql://` is the recommended prefix according to PostgreSQL's documentation: http://www.postgresql.org/docs/9.3/static/libpq-connect.html#LIBPQ-CONNSTRING But pg web only supports `postgres://`

**Comment by cbandy** [comment]
Support was added to lib/pq [in April](https://github.com/lib/pq/compare/ec83aaae1acf89e469d8e5cb19a70c4800ab9513%5E...e51fec16be7847e24d0270a5ce1f95cf2482b5e9).

**Comment by sosedoff** [comment]
Implemented in master.
