### ISSUE TITLE
Issue with downloading the CSV 

### ISSUE THREAD

**Issue by enr2114** [sosedoff/pgweb#95]
Runs the query but when I download csv I get an error message.  I believe its because I'm using "+" to add two different columns

**Comment by sosedoff** [comment]
Could you provide a more detailed example?

**Comment by enr2114** [comment]
Hey,

So my query included a line "application_funders.amount +
COALESCE(application_prior_fundings.buyout_amount,0) as "total approved
amount" FROM applications "

I have no problem running the query but when I try to download it I get an
error "pg: syntax error at or near "COALESCE""

Thanks,
ELana

**Comment by sosedoff** [comment]
Thanks, i'll have a look later today

**Comment by sosedoff** [comment]
Fixed in latest release
