### ISSUE TITLE
Special characters support

### ISSUE THREAD

**Issue by yarons** [sosedoff/pgweb#96]
I tried using this amazing tool and figured it doesn't read my password.

The password I'm using for my user is `%yaron11` and for some reason I get the following message (using web or cli):

```
Error: parse postgres://autheticated:%yaron11@localhost:5432/customerrecords?sslmode=disable: invalid URL escape "%ya"
```

**Comment by sosedoff** [comment]
Ah, i think someone mentioned about this before. Will fix.

**Comment by sosedoff** [comment]
Fixed in latest release. However, you should be using proper escaping for the full uri's

**Comment by yarons** [comment]
Confirmed, I must say I'm impressed, blazing fast and very easy to use, thank you for the wonderful tool!
