### ISSUE TITLE
Redshift support

### ISSUE THREAD

**Issue by abourget** [sosedoff/pgweb#97]
Would like to have redshift support.. 

is this still supported ? anyone took over ?

**Comment by lenguyenthedat** [comment]
It does work for me. But it doesn't show any tables on the left hand side, is that what happened to you?

**Comment by abourget** [comment]
Yes.. same here.. the table defs aren't defined in the same place perhaps.. I remember using "information_schema" or something like that. I know there are two ways of accessing the same meta info.

**Comment by lenguyenthedat** [comment]
Same problem with Amazon RDS (Postgresql) btw.

**Comment by sosedoff** [comment]
Amazon RDS should now be supported. I pushed support for multiple schemas into master.
