### ISSUE TITLE
about map function you use in client.query

### ISSUE THREAD

**Issue by goldalworming** [sosedoff/pgweb#98]
I read this on https://blog.golang.org/go-maps-in-action

Maps are not safe for concurrent use: it's not defined what happens when you read and write to them simultaneously. If you need to read from and write to a map from concurrently executing goroutines, the accesses must be mediated by some kind of synchronization mechanism. One common way to protect maps is with sync.RWMutex.

I see you use map but not rwmutex. do you use it because there is no other way to display dynamic struct from database and ignore lock since pgweb commonly use for local application or you have handle concurency with another way?

**Comment by sosedoff** [comment]
Which piece of code in particular are you talking about?

**Comment by goldalworming** [comment]
I think this one which generate object to return as json in pgweb


	func (client *Client) query(query string, args ...interface{}) (*Result, error) {
		rows, err := client.db.Queryx(query, args...)

		if err != nil {
			return nil, err
		}

		defer rows.Close()

		cols, err := rows.Columns()
		if err != nil {
			return nil, err
		}

		result := Result{Columns: cols}

		for rows.Next() {
			obj, err := rows.SliceScan()

			for i, item := range obj {
				if item == nil {
					obj[i] = nil
				} else {
					t := reflect.TypeOf(item).Kind().String()

					if t == "slice" {
						obj[i] = string(item.([]byte))
					}
				}
			}

			if err == nil {
				result.Rows = append(result.Rows, obj)
			}
		}

		return &result, nil
	}

**Comment by sosedoff** [comment]
I dont see any maps in the code you provided. Am i missing something ? `rows.SliceScan()` returns `[]interface{}` https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L540

**Comment by goldalworming** [comment]
ok, I'm sorry, I thought it was same with        
        arrayobj := make([]map[string]interface{}, 0)
        for rows.Next() {
            // get RawBytes from data
            err = rows.Scan(scanArgs...)
            if err != nil {
                panic(err.Error()) // proper error handling instead of panic in your app
            }

            var value string
            var vobj = make(map[string]interface{})
 .
 .
 .

thank you for give me direction to code in go
